// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CAuthentication_BeginAuthSessionViaCredentials_Response.proto

package com.chenerzhu.crawler.proxy.protobufs;

public final class CAuthenticationBeginAuthSessionViaCredentialsResponse {
  private CAuthenticationBeginAuthSessionViaCredentialsResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSEOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chenerzhu.crawler.proxy.protobufs.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 客户端ID
     * </pre>
     *
     * <code>int64 client_id = 1;</code>
     * @return The clientId.
     */
    long getClientId();

    /**
     * <pre>
     * 请求ID
     * </pre>
     *
     * <code>bytes request_id = 2;</code>
     * @return The requestId.
     */
    com.google.protobuf.ByteString getRequestId();

    /**
     * <pre>
     * 间隔时间
     * </pre>
     *
     * <code>int32 interval = 3;</code>
     * @return The interval.
     */
    int getInterval();

    /**
     * <pre>
     * Steam ID
     * </pre>
     *
     * <code>int64 steamid = 4;</code>
     * @return The steamid.
     */
    long getSteamid();

    /**
     * <pre>
     * 额外数据（如你提到的字符串）
     * </pre>
     *
     * <code>string additional_data = 5;</code>
     * @return The additionalData.
     */
    java.lang.String getAdditionalData();
    /**
     * <pre>
     * 额外数据（如你提到的字符串）
     * </pre>
     *
     * <code>string additional_data = 5;</code>
     * @return The bytes for additionalData.
     */
    com.google.protobuf.ByteString
        getAdditionalDataBytes();
  }
  /**
   * Protobuf type {@code com.chenerzhu.crawler.proxy.protobufs.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE}
   */
  public static final class CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chenerzhu.crawler.proxy.protobufs.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE)
      CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSEOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE.newBuilder() to construct.
    private CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE() {
      requestId_ = com.google.protobuf.ByteString.EMPTY;
      additionalData_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE.class, com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE.Builder.class);
    }

    public static final int CLIENT_ID_FIELD_NUMBER = 1;
    private long clientId_;
    /**
     * <pre>
     * 客户端ID
     * </pre>
     *
     * <code>int64 client_id = 1;</code>
     * @return The clientId.
     */
    @java.lang.Override
    public long getClientId() {
      return clientId_;
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString requestId_;
    /**
     * <pre>
     * 请求ID
     * </pre>
     *
     * <code>bytes request_id = 2;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRequestId() {
      return requestId_;
    }

    public static final int INTERVAL_FIELD_NUMBER = 3;
    private int interval_;
    /**
     * <pre>
     * 间隔时间
     * </pre>
     *
     * <code>int32 interval = 3;</code>
     * @return The interval.
     */
    @java.lang.Override
    public int getInterval() {
      return interval_;
    }

    public static final int STEAMID_FIELD_NUMBER = 4;
    private long steamid_;
    /**
     * <pre>
     * Steam ID
     * </pre>
     *
     * <code>int64 steamid = 4;</code>
     * @return The steamid.
     */
    @java.lang.Override
    public long getSteamid() {
      return steamid_;
    }

    public static final int ADDITIONAL_DATA_FIELD_NUMBER = 5;
    private volatile java.lang.Object additionalData_;
    /**
     * <pre>
     * 额外数据（如你提到的字符串）
     * </pre>
     *
     * <code>string additional_data = 5;</code>
     * @return The additionalData.
     */
    @java.lang.Override
    public java.lang.String getAdditionalData() {
      java.lang.Object ref = additionalData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        additionalData_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 额外数据（如你提到的字符串）
     * </pre>
     *
     * <code>string additional_data = 5;</code>
     * @return The bytes for additionalData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAdditionalDataBytes() {
      java.lang.Object ref = additionalData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        additionalData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientId_ != 0L) {
        output.writeInt64(1, clientId_);
      }
      if (!requestId_.isEmpty()) {
        output.writeBytes(2, requestId_);
      }
      if (interval_ != 0) {
        output.writeInt32(3, interval_);
      }
      if (steamid_ != 0L) {
        output.writeInt64(4, steamid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(additionalData_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, additionalData_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clientId_);
      }
      if (!requestId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, requestId_);
      }
      if (interval_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, interval_);
      }
      if (steamid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, steamid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(additionalData_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, additionalData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE)) {
        return super.equals(obj);
      }
      com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE other = (com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE) obj;

      if (getClientId()
          != other.getClientId()) return false;
      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (getInterval()
          != other.getInterval()) return false;
      if (getSteamid()
          != other.getSteamid()) return false;
      if (!getAdditionalData()
          .equals(other.getAdditionalData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getClientId());
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + INTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + getInterval();
      hash = (37 * hash) + STEAMID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSteamid());
      hash = (37 * hash) + ADDITIONAL_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getAdditionalData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.chenerzhu.crawler.proxy.protobufs.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chenerzhu.crawler.proxy.protobufs.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE)
        com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSEOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE.class, com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE.Builder.class);
      }

      // Construct using com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientId_ = 0L;

        requestId_ = com.google.protobuf.ByteString.EMPTY;

        interval_ = 0;

        steamid_ = 0L;

        additionalData_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE_descriptor;
      }

      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE getDefaultInstanceForType() {
        return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE.getDefaultInstance();
      }

      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE build() {
        com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE buildPartial() {
        com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE result = new com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE(this);
        result.clientId_ = clientId_;
        result.requestId_ = requestId_;
        result.interval_ = interval_;
        result.steamid_ = steamid_;
        result.additionalData_ = additionalData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE) {
          return mergeFrom((com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE other) {
        if (other == com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE.getDefaultInstance()) return this;
        if (other.getClientId() != 0L) {
          setClientId(other.getClientId());
        }
        if (other.getRequestId() != com.google.protobuf.ByteString.EMPTY) {
          setRequestId(other.getRequestId());
        }
        if (other.getInterval() != 0) {
          setInterval(other.getInterval());
        }
        if (other.getSteamid() != 0L) {
          setSteamid(other.getSteamid());
        }
        if (!other.getAdditionalData().isEmpty()) {
          additionalData_ = other.additionalData_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                clientId_ = input.readInt64();

                break;
              } // case 8
              case 18: {
                requestId_ = input.readBytes();

                break;
              } // case 18
              case 24: {
                interval_ = input.readInt32();

                break;
              } // case 24
              case 32: {
                steamid_ = input.readInt64();

                break;
              } // case 32
              case 42: {
                additionalData_ = input.readStringRequireUtf8();

                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long clientId_ ;
      /**
       * <pre>
       * 客户端ID
       * </pre>
       *
       * <code>int64 client_id = 1;</code>
       * @return The clientId.
       */
      @java.lang.Override
      public long getClientId() {
        return clientId_;
      }
      /**
       * <pre>
       * 客户端ID
       * </pre>
       *
       * <code>int64 client_id = 1;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(long value) {
        
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端ID
       * </pre>
       *
       * <code>int64 client_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString requestId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 请求ID
       * </pre>
       *
       * <code>bytes request_id = 2;</code>
       * @return The requestId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRequestId() {
        return requestId_;
      }
      /**
       * <pre>
       * 请求ID
       * </pre>
       *
       * <code>bytes request_id = 2;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求ID
       * </pre>
       *
       * <code>bytes request_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }

      private int interval_ ;
      /**
       * <pre>
       * 间隔时间
       * </pre>
       *
       * <code>int32 interval = 3;</code>
       * @return The interval.
       */
      @java.lang.Override
      public int getInterval() {
        return interval_;
      }
      /**
       * <pre>
       * 间隔时间
       * </pre>
       *
       * <code>int32 interval = 3;</code>
       * @param value The interval to set.
       * @return This builder for chaining.
       */
      public Builder setInterval(int value) {
        
        interval_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 间隔时间
       * </pre>
       *
       * <code>int32 interval = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterval() {
        
        interval_ = 0;
        onChanged();
        return this;
      }

      private long steamid_ ;
      /**
       * <pre>
       * Steam ID
       * </pre>
       *
       * <code>int64 steamid = 4;</code>
       * @return The steamid.
       */
      @java.lang.Override
      public long getSteamid() {
        return steamid_;
      }
      /**
       * <pre>
       * Steam ID
       * </pre>
       *
       * <code>int64 steamid = 4;</code>
       * @param value The steamid to set.
       * @return This builder for chaining.
       */
      public Builder setSteamid(long value) {
        
        steamid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Steam ID
       * </pre>
       *
       * <code>int64 steamid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSteamid() {
        
        steamid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object additionalData_ = "";
      /**
       * <pre>
       * 额外数据（如你提到的字符串）
       * </pre>
       *
       * <code>string additional_data = 5;</code>
       * @return The additionalData.
       */
      public java.lang.String getAdditionalData() {
        java.lang.Object ref = additionalData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          additionalData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 额外数据（如你提到的字符串）
       * </pre>
       *
       * <code>string additional_data = 5;</code>
       * @return The bytes for additionalData.
       */
      public com.google.protobuf.ByteString
          getAdditionalDataBytes() {
        java.lang.Object ref = additionalData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          additionalData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 额外数据（如你提到的字符串）
       * </pre>
       *
       * <code>string additional_data = 5;</code>
       * @param value The additionalData to set.
       * @return This builder for chaining.
       */
      public Builder setAdditionalData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        additionalData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 额外数据（如你提到的字符串）
       * </pre>
       *
       * <code>string additional_data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAdditionalData() {
        
        additionalData_ = getDefaultInstance().getAdditionalData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 额外数据（如你提到的字符串）
       * </pre>
       *
       * <code>string additional_data = 5;</code>
       * @param value The bytes for additionalData to set.
       * @return This builder for chaining.
       */
      public Builder setAdditionalDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        additionalData_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chenerzhu.crawler.proxy.protobufs.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE)
    }

    // @@protoc_insertion_point(class_scope:com.chenerzhu.crawler.proxy.protobufs.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE)
    private static final com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE();
    }

    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE>
        PARSER = new com.google.protobuf.AbstractParser<CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE>() {
      @java.lang.Override
      public CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chenerzhu_crawler_proxy_protobufs_CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chenerzhu_crawler_proxy_protobufs_CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=CAuthentication_BeginAuthSessionViaCre" +
      "dentials_Response.proto\022%com.chenerzhu.c" +
      "rawler.proxy.protobufs\"\234\001\n7CAUTHENTICATI" +
      "ON_BEGINAUTHSESSIONVIACREDENTIALS_RESPON" +
      "SE\022\021\n\tclient_id\030\001 \001(\003\022\022\n\nrequest_id\030\002 \001(" +
      "\014\022\020\n\010interval\030\003 \001(\005\022\017\n\007steamid\030\004 \001(\003\022\027\n\017" +
      "additional_data\030\005 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_chenerzhu_crawler_proxy_protobufs_CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chenerzhu_crawler_proxy_protobufs_CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chenerzhu_crawler_proxy_protobufs_CAUTHENTICATION_BEGINAUTHSESSIONVIACREDENTIALS_RESPONSE_descriptor,
        new java.lang.String[] { "ClientId", "RequestId", "Interval", "Steamid", "AdditionalData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
