// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CAuthentication_BeginAuthSessionViaCredentials_Request.proto

package com.chenerzhu.crawler.proxy.protobufs;

public final class CAuthenticationBeginAuthSessionViaCredentialsRequest {
  private CAuthenticationBeginAuthSessionViaCredentialsRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Auth Token Platform Type Enum
   * </pre>
   *
   * Protobuf enum {@code com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType}
   */
  public enum EAuthTokenPlatformType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_EAuthTokenPlatformType_Unknown = 0;</code>
     */
    k_EAuthTokenPlatformType_Unknown(0),
    /**
     * <code>k_EAuthTokenPlatformType_MobileApp = 1;</code>
     */
    k_EAuthTokenPlatformType_MobileApp(1),
    /**
     * <code>k_EAuthTokenPlatformType_DesktopApp = 2;</code>
     */
    k_EAuthTokenPlatformType_DesktopApp(2),
    /**
     * <code>k_EAuthTokenPlatformType_WebApp = 3;</code>
     */
    k_EAuthTokenPlatformType_WebApp(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>k_EAuthTokenPlatformType_Unknown = 0;</code>
     */
    public static final int k_EAuthTokenPlatformType_Unknown_VALUE = 0;
    /**
     * <code>k_EAuthTokenPlatformType_MobileApp = 1;</code>
     */
    public static final int k_EAuthTokenPlatformType_MobileApp_VALUE = 1;
    /**
     * <code>k_EAuthTokenPlatformType_DesktopApp = 2;</code>
     */
    public static final int k_EAuthTokenPlatformType_DesktopApp_VALUE = 2;
    /**
     * <code>k_EAuthTokenPlatformType_WebApp = 3;</code>
     */
    public static final int k_EAuthTokenPlatformType_WebApp_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static EAuthTokenPlatformType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EAuthTokenPlatformType forNumber(int value) {
      switch (value) {
        case 0: return k_EAuthTokenPlatformType_Unknown;
        case 1: return k_EAuthTokenPlatformType_MobileApp;
        case 2: return k_EAuthTokenPlatformType_DesktopApp;
        case 3: return k_EAuthTokenPlatformType_WebApp;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EAuthTokenPlatformType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EAuthTokenPlatformType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EAuthTokenPlatformType>() {
            public EAuthTokenPlatformType findValueByNumber(int number) {
              return EAuthTokenPlatformType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CAuthenticationBeginAuthSessionViaCredentialsRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final EAuthTokenPlatformType[] VALUES = values();

    public static EAuthTokenPlatformType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EAuthTokenPlatformType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType)
  }

  /**
   * <pre>
   * Session Persistence Enum
   * </pre>
   *
   * Protobuf enum {@code com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence}
   */
  public enum ESessionPersistence
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_ESessionPersistence_Unknown = 0;</code>
     */
    k_ESessionPersistence_Unknown(0),
    /**
     * <code>k_ESessionPersistence_Persistent = 1;</code>
     */
    k_ESessionPersistence_Persistent(1),
    /**
     * <code>k_ESessionPersistence_NonPersistent = 2;</code>
     */
    k_ESessionPersistence_NonPersistent(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>k_ESessionPersistence_Unknown = 0;</code>
     */
    public static final int k_ESessionPersistence_Unknown_VALUE = 0;
    /**
     * <code>k_ESessionPersistence_Persistent = 1;</code>
     */
    public static final int k_ESessionPersistence_Persistent_VALUE = 1;
    /**
     * <code>k_ESessionPersistence_NonPersistent = 2;</code>
     */
    public static final int k_ESessionPersistence_NonPersistent_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ESessionPersistence valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ESessionPersistence forNumber(int value) {
      switch (value) {
        case 0: return k_ESessionPersistence_Unknown;
        case 1: return k_ESessionPersistence_Persistent;
        case 2: return k_ESessionPersistence_NonPersistent;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ESessionPersistence>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ESessionPersistence> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ESessionPersistence>() {
            public ESessionPersistence findValueByNumber(int number) {
              return ESessionPersistence.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CAuthenticationBeginAuthSessionViaCredentialsRequest.getDescriptor().getEnumTypes().get(1);
    }

    private static final ESessionPersistence[] VALUES = values();

    public static ESessionPersistence valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ESessionPersistence(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence)
  }

  public interface CAuthentication_BeginAuthSessionViaCredentials_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Account name
     * </pre>
     *
     * <code>string account_name = 1;</code>
     * @return The accountName.
     */
    String getAccountName();
    /**
     * <pre>
     * Account name
     * </pre>
     *
     * <code>string account_name = 1;</code>
     * @return The bytes for accountName.
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    /**
     * <pre>
     * Encrypted password
     * </pre>
     *
     * <code>bytes encrypted_password = 2;</code>
     * @return The encryptedPassword.
     */
    com.google.protobuf.ByteString getEncryptedPassword();

    /**
     * <pre>
     * Timestamp of encryption
     * </pre>
     *
     * <code>int64 encryption_timestamp = 3;</code>
     * @return The encryptionTimestamp.
     */
    long getEncryptionTimestamp();

    /**
     * <pre>
     * Whether to remember login
     * </pre>
     *
     * <code>bool remember_login = 4;</code>
     * @return The rememberLogin.
     */
    boolean getRememberLogin();

    /**
     * <pre>
     * Platform type
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 5;</code>
     * @return The enum numeric value on the wire for platformType.
     */
    int getPlatformTypeValue();
    /**
     * <pre>
     * Platform type
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 5;</code>
     * @return The platformType.
     */
    EAuthTokenPlatformType getPlatformType();

    /**
     * <pre>
     * Website identifier
     * </pre>
     *
     * <code>string website_id = 6;</code>
     * @return The websiteId.
     */
    String getWebsiteId();
    /**
     * <pre>
     * Website identifier
     * </pre>
     *
     * <code>string website_id = 6;</code>
     * @return The bytes for websiteId.
     */
    com.google.protobuf.ByteString
        getWebsiteIdBytes();

    /**
     * <pre>
     * Session persistence
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
     * @return The enum numeric value on the wire for persistence.
     */
    int getPersistenceValue();
    /**
     * <pre>
     * Session persistence
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
     * @return The persistence.
     */
    ESessionPersistence getPersistence();

    /**
     * <pre>
     * Friendly name of the device
     * </pre>
     *
     * <code>string device_friendly_name = 8;</code>
     * @return The deviceFriendlyName.
     */
    String getDeviceFriendlyName();
    /**
     * <pre>
     * Friendly name of the device
     * </pre>
     *
     * <code>string device_friendly_name = 8;</code>
     * @return The bytes for deviceFriendlyName.
     */
    com.google.protobuf.ByteString
        getDeviceFriendlyNameBytes();
  }
  /**
   * <pre>
   * Request message for beginning auth session via credentials
   * </pre>
   *
   * Protobuf type {@code com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request}
   */
  public static final class CAuthentication_BeginAuthSessionViaCredentials_Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request)
      CAuthentication_BeginAuthSessionViaCredentials_RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CAuthentication_BeginAuthSessionViaCredentials_Request.newBuilder() to construct.
    private CAuthentication_BeginAuthSessionViaCredentials_Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CAuthentication_BeginAuthSessionViaCredentials_Request() {
      accountName_ = "";
      encryptedPassword_ = com.google.protobuf.ByteString.EMPTY;
      platformType_ = 0;
      websiteId_ = "";
      persistence_ = 0;
      deviceFriendlyName_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CAuthentication_BeginAuthSessionViaCredentials_Request();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CAuthenticationBeginAuthSessionViaCredentialsRequest.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CAuthenticationBeginAuthSessionViaCredentialsRequest.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CAuthentication_BeginAuthSessionViaCredentials_Request.class, Builder.class);
    }

    public static final int ACCOUNT_NAME_FIELD_NUMBER = 1;
    private volatile Object accountName_;
    /**
     * <pre>
     * Account name
     * </pre>
     *
     * <code>string account_name = 1;</code>
     * @return The accountName.
     */
    @Override
    public String getAccountName() {
      Object ref = accountName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        accountName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Account name
     * </pre>
     *
     * <code>string account_name = 1;</code>
     * @return The bytes for accountName.
     */
    @Override
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      Object ref = accountName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPTED_PASSWORD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString encryptedPassword_;
    /**
     * <pre>
     * Encrypted password
     * </pre>
     *
     * <code>bytes encrypted_password = 2;</code>
     * @return The encryptedPassword.
     */
    @Override
    public com.google.protobuf.ByteString getEncryptedPassword() {
      return encryptedPassword_;
    }

    public static final int ENCRYPTION_TIMESTAMP_FIELD_NUMBER = 3;
    private long encryptionTimestamp_;
    /**
     * <pre>
     * Timestamp of encryption
     * </pre>
     *
     * <code>int64 encryption_timestamp = 3;</code>
     * @return The encryptionTimestamp.
     */
    @Override
    public long getEncryptionTimestamp() {
      return encryptionTimestamp_;
    }

    public static final int REMEMBER_LOGIN_FIELD_NUMBER = 4;
    private boolean rememberLogin_;
    /**
     * <pre>
     * Whether to remember login
     * </pre>
     *
     * <code>bool remember_login = 4;</code>
     * @return The rememberLogin.
     */
    @Override
    public boolean getRememberLogin() {
      return rememberLogin_;
    }

    public static final int PLATFORM_TYPE_FIELD_NUMBER = 5;
    private int platformType_;
    /**
     * <pre>
     * Platform type
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 5;</code>
     * @return The enum numeric value on the wire for platformType.
     */
    @Override public int getPlatformTypeValue() {
      return platformType_;
    }
    /**
     * <pre>
     * Platform type
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 5;</code>
     * @return The platformType.
     */
    @Override public EAuthTokenPlatformType getPlatformType() {
      @SuppressWarnings("deprecation")
      EAuthTokenPlatformType result = EAuthTokenPlatformType.valueOf(platformType_);
      return result == null ? EAuthTokenPlatformType.UNRECOGNIZED : result;
    }

    public static final int WEBSITE_ID_FIELD_NUMBER = 6;
    private volatile Object websiteId_;
    /**
     * <pre>
     * Website identifier
     * </pre>
     *
     * <code>string website_id = 6;</code>
     * @return The websiteId.
     */
    @Override
    public String getWebsiteId() {
      Object ref = websiteId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        websiteId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Website identifier
     * </pre>
     *
     * <code>string website_id = 6;</code>
     * @return The bytes for websiteId.
     */
    @Override
    public com.google.protobuf.ByteString
        getWebsiteIdBytes() {
      Object ref = websiteId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        websiteId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSISTENCE_FIELD_NUMBER = 7;
    private int persistence_;
    /**
     * <pre>
     * Session persistence
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
     * @return The enum numeric value on the wire for persistence.
     */
    @Override public int getPersistenceValue() {
      return persistence_;
    }
    /**
     * <pre>
     * Session persistence
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
     * @return The persistence.
     */
    @Override public ESessionPersistence getPersistence() {
      @SuppressWarnings("deprecation")
      ESessionPersistence result = ESessionPersistence.valueOf(persistence_);
      return result == null ? ESessionPersistence.UNRECOGNIZED : result;
    }

    public static final int DEVICE_FRIENDLY_NAME_FIELD_NUMBER = 8;
    private volatile Object deviceFriendlyName_;
    /**
     * <pre>
     * Friendly name of the device
     * </pre>
     *
     * <code>string device_friendly_name = 8;</code>
     * @return The deviceFriendlyName.
     */
    @Override
    public String getDeviceFriendlyName() {
      Object ref = deviceFriendlyName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceFriendlyName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Friendly name of the device
     * </pre>
     *
     * <code>string device_friendly_name = 8;</code>
     * @return The bytes for deviceFriendlyName.
     */
    @Override
    public com.google.protobuf.ByteString
        getDeviceFriendlyNameBytes() {
      Object ref = deviceFriendlyName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceFriendlyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountName_);
      }
      if (!encryptedPassword_.isEmpty()) {
        output.writeBytes(2, encryptedPassword_);
      }
      if (encryptionTimestamp_ != 0L) {
        output.writeInt64(3, encryptionTimestamp_);
      }
      if (rememberLogin_ != false) {
        output.writeBool(4, rememberLogin_);
      }
      if (platformType_ != EAuthTokenPlatformType.k_EAuthTokenPlatformType_Unknown.getNumber()) {
        output.writeEnum(5, platformType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(websiteId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, websiteId_);
      }
      if (persistence_ != ESessionPersistence.k_ESessionPersistence_Unknown.getNumber()) {
        output.writeEnum(7, persistence_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceFriendlyName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, deviceFriendlyName_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountName_);
      }
      if (!encryptedPassword_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, encryptedPassword_);
      }
      if (encryptionTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, encryptionTimestamp_);
      }
      if (rememberLogin_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, rememberLogin_);
      }
      if (platformType_ != EAuthTokenPlatformType.k_EAuthTokenPlatformType_Unknown.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, platformType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(websiteId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, websiteId_);
      }
      if (persistence_ != ESessionPersistence.k_ESessionPersistence_Unknown.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, persistence_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceFriendlyName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, deviceFriendlyName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CAuthentication_BeginAuthSessionViaCredentials_Request)) {
        return super.equals(obj);
      }
      CAuthentication_BeginAuthSessionViaCredentials_Request other = (CAuthentication_BeginAuthSessionViaCredentials_Request) obj;

      if (!getAccountName()
          .equals(other.getAccountName())) return false;
      if (!getEncryptedPassword()
          .equals(other.getEncryptedPassword())) return false;
      if (getEncryptionTimestamp()
          != other.getEncryptionTimestamp()) return false;
      if (getRememberLogin()
          != other.getRememberLogin()) return false;
      if (platformType_ != other.platformType_) return false;
      if (!getWebsiteId()
          .equals(other.getWebsiteId())) return false;
      if (persistence_ != other.persistence_) return false;
      if (!getDeviceFriendlyName()
          .equals(other.getDeviceFriendlyName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCOUNT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getAccountName().hashCode();
      hash = (37 * hash) + ENCRYPTED_PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedPassword().hashCode();
      hash = (37 * hash) + ENCRYPTION_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEncryptionTimestamp());
      hash = (37 * hash) + REMEMBER_LOGIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRememberLogin());
      hash = (37 * hash) + PLATFORM_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + platformType_;
      hash = (37 * hash) + WEBSITE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWebsiteId().hashCode();
      hash = (37 * hash) + PERSISTENCE_FIELD_NUMBER;
      hash = (53 * hash) + persistence_;
      hash = (37 * hash) + DEVICE_FRIENDLY_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceFriendlyName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CAuthentication_BeginAuthSessionViaCredentials_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CAuthentication_BeginAuthSessionViaCredentials_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CAuthentication_BeginAuthSessionViaCredentials_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Request message for beginning auth session via credentials
     * </pre>
     *
     * Protobuf type {@code com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request)
        CAuthentication_BeginAuthSessionViaCredentials_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CAuthenticationBeginAuthSessionViaCredentialsRequest.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CAuthenticationBeginAuthSessionViaCredentialsRequest.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CAuthentication_BeginAuthSessionViaCredentials_Request.class, Builder.class);
      }

      // Construct using com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        accountName_ = "";

        encryptedPassword_ = com.google.protobuf.ByteString.EMPTY;

        encryptionTimestamp_ = 0L;

        rememberLogin_ = false;

        platformType_ = 0;

        websiteId_ = "";

        persistence_ = 0;

        deviceFriendlyName_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CAuthenticationBeginAuthSessionViaCredentialsRequest.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_descriptor;
      }

      @Override
      public CAuthentication_BeginAuthSessionViaCredentials_Request getDefaultInstanceForType() {
        return CAuthentication_BeginAuthSessionViaCredentials_Request.getDefaultInstance();
      }

      @Override
      public CAuthentication_BeginAuthSessionViaCredentials_Request build() {
        CAuthentication_BeginAuthSessionViaCredentials_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CAuthentication_BeginAuthSessionViaCredentials_Request buildPartial() {
        CAuthentication_BeginAuthSessionViaCredentials_Request result = new CAuthentication_BeginAuthSessionViaCredentials_Request(this);
        result.accountName_ = accountName_;
        result.encryptedPassword_ = encryptedPassword_;
        result.encryptionTimestamp_ = encryptionTimestamp_;
        result.rememberLogin_ = rememberLogin_;
        result.platformType_ = platformType_;
        result.websiteId_ = websiteId_;
        result.persistence_ = persistence_;
        result.deviceFriendlyName_ = deviceFriendlyName_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CAuthentication_BeginAuthSessionViaCredentials_Request) {
          return mergeFrom((CAuthentication_BeginAuthSessionViaCredentials_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CAuthentication_BeginAuthSessionViaCredentials_Request other) {
        if (other == CAuthentication_BeginAuthSessionViaCredentials_Request.getDefaultInstance()) return this;
        if (!other.getAccountName().isEmpty()) {
          accountName_ = other.accountName_;
          onChanged();
        }
        if (other.getEncryptedPassword() != com.google.protobuf.ByteString.EMPTY) {
          setEncryptedPassword(other.getEncryptedPassword());
        }
        if (other.getEncryptionTimestamp() != 0L) {
          setEncryptionTimestamp(other.getEncryptionTimestamp());
        }
        if (other.getRememberLogin() != false) {
          setRememberLogin(other.getRememberLogin());
        }
        if (other.platformType_ != 0) {
          setPlatformTypeValue(other.getPlatformTypeValue());
        }
        if (!other.getWebsiteId().isEmpty()) {
          websiteId_ = other.websiteId_;
          onChanged();
        }
        if (other.persistence_ != 0) {
          setPersistenceValue(other.getPersistenceValue());
        }
        if (!other.getDeviceFriendlyName().isEmpty()) {
          deviceFriendlyName_ = other.deviceFriendlyName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                accountName_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                encryptedPassword_ = input.readBytes();

                break;
              } // case 18
              case 24: {
                encryptionTimestamp_ = input.readInt64();

                break;
              } // case 24
              case 32: {
                rememberLogin_ = input.readBool();

                break;
              } // case 32
              case 40: {
                platformType_ = input.readEnum();

                break;
              } // case 40
              case 50: {
                websiteId_ = input.readStringRequireUtf8();

                break;
              } // case 50
              case 56: {
                persistence_ = input.readEnum();

                break;
              } // case 56
              case 66: {
                deviceFriendlyName_ = input.readStringRequireUtf8();

                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private Object accountName_ = "";
      /**
       * <pre>
       * Account name
       * </pre>
       *
       * <code>string account_name = 1;</code>
       * @return The accountName.
       */
      public String getAccountName() {
        Object ref = accountName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          accountName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Account name
       * </pre>
       *
       * <code>string account_name = 1;</code>
       * @return The bytes for accountName.
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Account name
       * </pre>
       *
       * <code>string account_name = 1;</code>
       * @param value The accountName to set.
       * @return This builder for chaining.
       */
      public Builder setAccountName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accountName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Account name
       * </pre>
       *
       * <code>string account_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountName() {
        
        accountName_ = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Account name
       * </pre>
       *
       * <code>string account_name = 1;</code>
       * @param value The bytes for accountName to set.
       * @return This builder for chaining.
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accountName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encryptedPassword_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Encrypted password
       * </pre>
       *
       * <code>bytes encrypted_password = 2;</code>
       * @return The encryptedPassword.
       */
      @Override
      public com.google.protobuf.ByteString getEncryptedPassword() {
        return encryptedPassword_;
      }
      /**
       * <pre>
       * Encrypted password
       * </pre>
       *
       * <code>bytes encrypted_password = 2;</code>
       * @param value The encryptedPassword to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedPassword(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encryptedPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Encrypted password
       * </pre>
       *
       * <code>bytes encrypted_password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptedPassword() {
        
        encryptedPassword_ = getDefaultInstance().getEncryptedPassword();
        onChanged();
        return this;
      }

      private long encryptionTimestamp_ ;
      /**
       * <pre>
       * Timestamp of encryption
       * </pre>
       *
       * <code>int64 encryption_timestamp = 3;</code>
       * @return The encryptionTimestamp.
       */
      @Override
      public long getEncryptionTimestamp() {
        return encryptionTimestamp_;
      }
      /**
       * <pre>
       * Timestamp of encryption
       * </pre>
       *
       * <code>int64 encryption_timestamp = 3;</code>
       * @param value The encryptionTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptionTimestamp(long value) {
        
        encryptionTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timestamp of encryption
       * </pre>
       *
       * <code>int64 encryption_timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptionTimestamp() {
        
        encryptionTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private boolean rememberLogin_ ;
      /**
       * <pre>
       * Whether to remember login
       * </pre>
       *
       * <code>bool remember_login = 4;</code>
       * @return The rememberLogin.
       */
      @Override
      public boolean getRememberLogin() {
        return rememberLogin_;
      }
      /**
       * <pre>
       * Whether to remember login
       * </pre>
       *
       * <code>bool remember_login = 4;</code>
       * @param value The rememberLogin to set.
       * @return This builder for chaining.
       */
      public Builder setRememberLogin(boolean value) {
        
        rememberLogin_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether to remember login
       * </pre>
       *
       * <code>bool remember_login = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRememberLogin() {
        
        rememberLogin_ = false;
        onChanged();
        return this;
      }

      private int platformType_ = 0;
      /**
       * <pre>
       * Platform type
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 5;</code>
       * @return The enum numeric value on the wire for platformType.
       */
      @Override public int getPlatformTypeValue() {
        return platformType_;
      }
      /**
       * <pre>
       * Platform type
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 5;</code>
       * @param value The enum numeric value on the wire for platformType to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformTypeValue(int value) {
        
        platformType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Platform type
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 5;</code>
       * @return The platformType.
       */
      @Override
      public EAuthTokenPlatformType getPlatformType() {
        @SuppressWarnings("deprecation")
        EAuthTokenPlatformType result = EAuthTokenPlatformType.valueOf(platformType_);
        return result == null ? EAuthTokenPlatformType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Platform type
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 5;</code>
       * @param value The platformType to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformType(EAuthTokenPlatformType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        platformType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Platform type
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlatformType() {
        
        platformType_ = 0;
        onChanged();
        return this;
      }

      private Object websiteId_ = "";
      /**
       * <pre>
       * Website identifier
       * </pre>
       *
       * <code>string website_id = 6;</code>
       * @return The websiteId.
       */
      public String getWebsiteId() {
        Object ref = websiteId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          websiteId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Website identifier
       * </pre>
       *
       * <code>string website_id = 6;</code>
       * @return The bytes for websiteId.
       */
      public com.google.protobuf.ByteString
          getWebsiteIdBytes() {
        Object ref = websiteId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          websiteId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Website identifier
       * </pre>
       *
       * <code>string website_id = 6;</code>
       * @param value The websiteId to set.
       * @return This builder for chaining.
       */
      public Builder setWebsiteId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        websiteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Website identifier
       * </pre>
       *
       * <code>string website_id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearWebsiteId() {
        
        websiteId_ = getDefaultInstance().getWebsiteId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Website identifier
       * </pre>
       *
       * <code>string website_id = 6;</code>
       * @param value The bytes for websiteId to set.
       * @return This builder for chaining.
       */
      public Builder setWebsiteIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        websiteId_ = value;
        onChanged();
        return this;
      }

      private int persistence_ = 0;
      /**
       * <pre>
       * Session persistence
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
       * @return The enum numeric value on the wire for persistence.
       */
      @Override public int getPersistenceValue() {
        return persistence_;
      }
      /**
       * <pre>
       * Session persistence
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
       * @param value The enum numeric value on the wire for persistence to set.
       * @return This builder for chaining.
       */
      public Builder setPersistenceValue(int value) {
        
        persistence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Session persistence
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
       * @return The persistence.
       */
      @Override
      public ESessionPersistence getPersistence() {
        @SuppressWarnings("deprecation")
        ESessionPersistence result = ESessionPersistence.valueOf(persistence_);
        return result == null ? ESessionPersistence.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Session persistence
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
       * @param value The persistence to set.
       * @return This builder for chaining.
       */
      public Builder setPersistence(ESessionPersistence value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        persistence_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Session persistence
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPersistence() {
        
        persistence_ = 0;
        onChanged();
        return this;
      }

      private Object deviceFriendlyName_ = "";
      /**
       * <pre>
       * Friendly name of the device
       * </pre>
       *
       * <code>string device_friendly_name = 8;</code>
       * @return The deviceFriendlyName.
       */
      public String getDeviceFriendlyName() {
        Object ref = deviceFriendlyName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceFriendlyName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Friendly name of the device
       * </pre>
       *
       * <code>string device_friendly_name = 8;</code>
       * @return The bytes for deviceFriendlyName.
       */
      public com.google.protobuf.ByteString
          getDeviceFriendlyNameBytes() {
        Object ref = deviceFriendlyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceFriendlyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Friendly name of the device
       * </pre>
       *
       * <code>string device_friendly_name = 8;</code>
       * @param value The deviceFriendlyName to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceFriendlyName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceFriendlyName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Friendly name of the device
       * </pre>
       *
       * <code>string device_friendly_name = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceFriendlyName() {
        
        deviceFriendlyName_ = getDefaultInstance().getDeviceFriendlyName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Friendly name of the device
       * </pre>
       *
       * <code>string device_friendly_name = 8;</code>
       * @param value The bytes for deviceFriendlyName to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceFriendlyNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceFriendlyName_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request)
    }

    // @@protoc_insertion_point(class_scope:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request)
    private static final CAuthentication_BeginAuthSessionViaCredentials_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CAuthentication_BeginAuthSessionViaCredentials_Request();
    }

    public static CAuthentication_BeginAuthSessionViaCredentials_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CAuthentication_BeginAuthSessionViaCredentials_Request>
        PARSER = new com.google.protobuf.AbstractParser<CAuthentication_BeginAuthSessionViaCredentials_Request>() {
      @Override
      public CAuthentication_BeginAuthSessionViaCredentials_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CAuthentication_BeginAuthSessionViaCredentials_Request> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CAuthentication_BeginAuthSessionViaCredentials_Request> getParserForType() {
      return PARSER;
    }

    @Override
    public CAuthentication_BeginAuthSessionViaCredentials_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n<CAuthentication_BeginAuthSessionViaCre" +
      "dentials_Request.proto\022%com.chenerzhu.cr" +
      "awler.proxy.protobufs\"\371\002\n6CAuthenticatio" +
      "n_BeginAuthSessionViaCredentials_Request" +
      "\022\024\n\014account_name\030\001 \001(\t\022\032\n\022encrypted_pass" +
      "word\030\002 \001(\014\022\034\n\024encryption_timestamp\030\003 \001(\003" +
      "\022\026\n\016remember_login\030\004 \001(\010\022T\n\rplatform_typ" +
      "e\030\005 \001(\0162=.com.chenerzhu.crawler.proxy.pr" +
      "otobufs.EAuthTokenPlatformType\022\022\n\nwebsit" +
      "e_id\030\006 \001(\t\022O\n\013persistence\030\007 \001(\0162:.com.ch" +
      "enerzhu.crawler.proxy.protobufs.ESession" +
      "Persistence\022\034\n\024device_friendly_name\030\010 \001(" +
      "\t*\264\001\n\026EAuthTokenPlatformType\022$\n k_EAuthT" +
      "okenPlatformType_Unknown\020\000\022&\n\"k_EAuthTok" +
      "enPlatformType_MobileApp\020\001\022\'\n#k_EAuthTok" +
      "enPlatformType_DesktopApp\020\002\022#\n\037k_EAuthTo" +
      "kenPlatformType_WebApp\020\003*\207\001\n\023ESessionPer" +
      "sistence\022!\n\035k_ESessionPersistence_Unknow" +
      "n\020\000\022$\n k_ESessionPersistence_Persistent\020" +
      "\001\022\'\n#k_ESessionPersistence_NonPersistent" +
      "\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_descriptor,
        new String[] { "AccountName", "EncryptedPassword", "EncryptionTimestamp", "RememberLogin", "PlatformType", "WebsiteId", "Persistence", "DeviceFriendlyName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
