// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CAuthentication_BeginAuthSessionViaCredentials_Response.proto

package com.chenerzhu.crawler.proxy.protobufs;

public final class CAuthenticationBeginAuthSessionViaCredentialsResponse {
  private CAuthenticationBeginAuthSessionViaCredentialsResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BeginAuthSessionViaCredentialsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chenerzhu.crawler.proxy.protobufs.BeginAuthSessionViaCredentialsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique identifier of requestor, also used for routing
     * </pre>
     *
     * <code>string client_id = 1;</code>
     * @return The clientId.
     */
    java.lang.String getClientId();
    /**
     * <pre>
     * Unique identifier of requestor, also used for routing
     * </pre>
     *
     * <code>string client_id = 1;</code>
     * @return The bytes for clientId.
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <pre>
     * Unique request ID to be presented by requestor at poll time - must not be transferred or displayed
     * </pre>
     *
     * <code>string request_id = 2;</code>
     * @return The requestId.
     */
    java.lang.String getRequestId();
    /**
     * <pre>
     * Unique request ID to be presented by requestor at poll time - must not be transferred or displayed
     * </pre>
     *
     * <code>string request_id = 2;</code>
     * @return The bytes for requestId.
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <pre>
     * Refresh interval with which requestor should call PollAuthSessionStatus
     * </pre>
     *
     * <code>int32 interval = 3;</code>
     * @return The interval.
     */
    int getInterval();

    /**
     * <pre>
     * The confirmation types that will be able to confirm the request
     * </pre>
     *
     * <code>repeated string allowed_confirmations = 4;</code>
     * @return A list containing the allowedConfirmations.
     */
    java.util.List<java.lang.String>
        getAllowedConfirmationsList();
    /**
     * <pre>
     * The confirmation types that will be able to confirm the request
     * </pre>
     *
     * <code>repeated string allowed_confirmations = 4;</code>
     * @return The count of allowedConfirmations.
     */
    int getAllowedConfirmationsCount();
    /**
     * <pre>
     * The confirmation types that will be able to confirm the request
     * </pre>
     *
     * <code>repeated string allowed_confirmations = 4;</code>
     * @param index The index of the element to return.
     * @return The allowedConfirmations at the given index.
     */
    java.lang.String getAllowedConfirmations(int index);
    /**
     * <pre>
     * The confirmation types that will be able to confirm the request
     * </pre>
     *
     * <code>repeated string allowed_confirmations = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the allowedConfirmations at the given index.
     */
    com.google.protobuf.ByteString
        getAllowedConfirmationsBytes(int index);

    /**
     * <pre>
     * SteamID of the account logging in - will only be included if the credentials were correct
     * </pre>
     *
     * <code>string steamid = 5;</code>
     * @return The steamid.
     */
    java.lang.String getSteamid();
    /**
     * <pre>
     * SteamID of the account logging in - will only be included if the credentials were correct
     * </pre>
     *
     * <code>string steamid = 5;</code>
     * @return The bytes for steamid.
     */
    com.google.protobuf.ByteString
        getSteamidBytes();

    /**
     * <pre>
     * Partial-authentication token - limited lifetime and scope, included only if credentials were correct
     * </pre>
     *
     * <code>string weak_token = 6;</code>
     * @return The weakToken.
     */
    java.lang.String getWeakToken();
    /**
     * <pre>
     * Partial-authentication token - limited lifetime and scope, included only if credentials were correct
     * </pre>
     *
     * <code>string weak_token = 6;</code>
     * @return The bytes for weakToken.
     */
    com.google.protobuf.ByteString
        getWeakTokenBytes();
  }
  /**
   * Protobuf type {@code com.chenerzhu.crawler.proxy.protobufs.BeginAuthSessionViaCredentialsResponse}
   */
  public static final class BeginAuthSessionViaCredentialsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chenerzhu.crawler.proxy.protobufs.BeginAuthSessionViaCredentialsResponse)
      BeginAuthSessionViaCredentialsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BeginAuthSessionViaCredentialsResponse.newBuilder() to construct.
    private BeginAuthSessionViaCredentialsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BeginAuthSessionViaCredentialsResponse() {
      clientId_ = "";
      requestId_ = "";
      allowedConfirmations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      steamid_ = "";
      weakToken_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BeginAuthSessionViaCredentialsResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_BeginAuthSessionViaCredentialsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_BeginAuthSessionViaCredentialsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse.class, com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse.Builder.class);
    }

    public static final int CLIENT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientId_;
    /**
     * <pre>
     * Unique identifier of requestor, also used for routing
     * </pre>
     *
     * <code>string client_id = 1;</code>
     * @return The clientId.
     */
    @java.lang.Override
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Unique identifier of requestor, also used for routing
     * </pre>
     *
     * <code>string client_id = 1;</code>
     * @return The bytes for clientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object requestId_;
    /**
     * <pre>
     * Unique request ID to be presented by requestor at poll time - must not be transferred or displayed
     * </pre>
     *
     * <code>string request_id = 2;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Unique request ID to be presented by requestor at poll time - must not be transferred or displayed
     * </pre>
     *
     * <code>string request_id = 2;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERVAL_FIELD_NUMBER = 3;
    private int interval_;
    /**
     * <pre>
     * Refresh interval with which requestor should call PollAuthSessionStatus
     * </pre>
     *
     * <code>int32 interval = 3;</code>
     * @return The interval.
     */
    @java.lang.Override
    public int getInterval() {
      return interval_;
    }

    public static final int ALLOWED_CONFIRMATIONS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList allowedConfirmations_;
    /**
     * <pre>
     * The confirmation types that will be able to confirm the request
     * </pre>
     *
     * <code>repeated string allowed_confirmations = 4;</code>
     * @return A list containing the allowedConfirmations.
     */
    public com.google.protobuf.ProtocolStringList
        getAllowedConfirmationsList() {
      return allowedConfirmations_;
    }
    /**
     * <pre>
     * The confirmation types that will be able to confirm the request
     * </pre>
     *
     * <code>repeated string allowed_confirmations = 4;</code>
     * @return The count of allowedConfirmations.
     */
    public int getAllowedConfirmationsCount() {
      return allowedConfirmations_.size();
    }
    /**
     * <pre>
     * The confirmation types that will be able to confirm the request
     * </pre>
     *
     * <code>repeated string allowed_confirmations = 4;</code>
     * @param index The index of the element to return.
     * @return The allowedConfirmations at the given index.
     */
    public java.lang.String getAllowedConfirmations(int index) {
      return allowedConfirmations_.get(index);
    }
    /**
     * <pre>
     * The confirmation types that will be able to confirm the request
     * </pre>
     *
     * <code>repeated string allowed_confirmations = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the allowedConfirmations at the given index.
     */
    public com.google.protobuf.ByteString
        getAllowedConfirmationsBytes(int index) {
      return allowedConfirmations_.getByteString(index);
    }

    public static final int STEAMID_FIELD_NUMBER = 5;
    private volatile java.lang.Object steamid_;
    /**
     * <pre>
     * SteamID of the account logging in - will only be included if the credentials were correct
     * </pre>
     *
     * <code>string steamid = 5;</code>
     * @return The steamid.
     */
    @java.lang.Override
    public java.lang.String getSteamid() {
      java.lang.Object ref = steamid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        steamid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * SteamID of the account logging in - will only be included if the credentials were correct
     * </pre>
     *
     * <code>string steamid = 5;</code>
     * @return The bytes for steamid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSteamidBytes() {
      java.lang.Object ref = steamid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        steamid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEAK_TOKEN_FIELD_NUMBER = 6;
    private volatile java.lang.Object weakToken_;
    /**
     * <pre>
     * Partial-authentication token - limited lifetime and scope, included only if credentials were correct
     * </pre>
     *
     * <code>string weak_token = 6;</code>
     * @return The weakToken.
     */
    @java.lang.Override
    public java.lang.String getWeakToken() {
      java.lang.Object ref = weakToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weakToken_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Partial-authentication token - limited lifetime and scope, included only if credentials were correct
     * </pre>
     *
     * <code>string weak_token = 6;</code>
     * @return The bytes for weakToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWeakTokenBytes() {
      java.lang.Object ref = weakToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weakToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, requestId_);
      }
      if (interval_ != 0) {
        output.writeInt32(3, interval_);
      }
      for (int i = 0; i < allowedConfirmations_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, allowedConfirmations_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(steamid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, steamid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(weakToken_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, weakToken_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, requestId_);
      }
      if (interval_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, interval_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < allowedConfirmations_.size(); i++) {
          dataSize += computeStringSizeNoTag(allowedConfirmations_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAllowedConfirmationsList().size();
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(steamid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, steamid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(weakToken_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, weakToken_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse)) {
        return super.equals(obj);
      }
      com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse other = (com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse) obj;

      if (!getClientId()
          .equals(other.getClientId())) return false;
      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (getInterval()
          != other.getInterval()) return false;
      if (!getAllowedConfirmationsList()
          .equals(other.getAllowedConfirmationsList())) return false;
      if (!getSteamid()
          .equals(other.getSteamid())) return false;
      if (!getWeakToken()
          .equals(other.getWeakToken())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + INTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + getInterval();
      if (getAllowedConfirmationsCount() > 0) {
        hash = (37 * hash) + ALLOWED_CONFIRMATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getAllowedConfirmationsList().hashCode();
      }
      hash = (37 * hash) + STEAMID_FIELD_NUMBER;
      hash = (53 * hash) + getSteamid().hashCode();
      hash = (37 * hash) + WEAK_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getWeakToken().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.chenerzhu.crawler.proxy.protobufs.BeginAuthSessionViaCredentialsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chenerzhu.crawler.proxy.protobufs.BeginAuthSessionViaCredentialsResponse)
        com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_BeginAuthSessionViaCredentialsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_BeginAuthSessionViaCredentialsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse.class, com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse.Builder.class);
      }

      // Construct using com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientId_ = "";

        requestId_ = "";

        interval_ = 0;

        allowedConfirmations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        steamid_ = "";

        weakToken_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_BeginAuthSessionViaCredentialsResponse_descriptor;
      }

      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse getDefaultInstanceForType() {
        return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse build() {
        com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse buildPartial() {
        com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse result = new com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse(this);
        int from_bitField0_ = bitField0_;
        result.clientId_ = clientId_;
        result.requestId_ = requestId_;
        result.interval_ = interval_;
        if (((bitField0_ & 0x00000001) != 0)) {
          allowedConfirmations_ = allowedConfirmations_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.allowedConfirmations_ = allowedConfirmations_;
        result.steamid_ = steamid_;
        result.weakToken_ = weakToken_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse) {
          return mergeFrom((com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse other) {
        if (other == com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.getInterval() != 0) {
          setInterval(other.getInterval());
        }
        if (!other.allowedConfirmations_.isEmpty()) {
          if (allowedConfirmations_.isEmpty()) {
            allowedConfirmations_ = other.allowedConfirmations_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAllowedConfirmationsIsMutable();
            allowedConfirmations_.addAll(other.allowedConfirmations_);
          }
          onChanged();
        }
        if (!other.getSteamid().isEmpty()) {
          steamid_ = other.steamid_;
          onChanged();
        }
        if (!other.getWeakToken().isEmpty()) {
          weakToken_ = other.weakToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                clientId_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                requestId_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 24: {
                interval_ = input.readInt32();

                break;
              } // case 24
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureAllowedConfirmationsIsMutable();
                allowedConfirmations_.add(s);
                break;
              } // case 34
              case 42: {
                steamid_ = input.readStringRequireUtf8();

                break;
              } // case 42
              case 50: {
                weakToken_ = input.readStringRequireUtf8();

                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object clientId_ = "";
      /**
       * <pre>
       * Unique identifier of requestor, also used for routing
       * </pre>
       *
       * <code>string client_id = 1;</code>
       * @return The clientId.
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Unique identifier of requestor, also used for routing
       * </pre>
       *
       * <code>string client_id = 1;</code>
       * @return The bytes for clientId.
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Unique identifier of requestor, also used for routing
       * </pre>
       *
       * <code>string client_id = 1;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier of requestor, also used for routing
       * </pre>
       *
       * <code>string client_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier of requestor, also used for routing
       * </pre>
       *
       * <code>string client_id = 1;</code>
       * @param value The bytes for clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <pre>
       * Unique request ID to be presented by requestor at poll time - must not be transferred or displayed
       * </pre>
       *
       * <code>string request_id = 2;</code>
       * @return The requestId.
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Unique request ID to be presented by requestor at poll time - must not be transferred or displayed
       * </pre>
       *
       * <code>string request_id = 2;</code>
       * @return The bytes for requestId.
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Unique request ID to be presented by requestor at poll time - must not be transferred or displayed
       * </pre>
       *
       * <code>string request_id = 2;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique request ID to be presented by requestor at poll time - must not be transferred or displayed
       * </pre>
       *
       * <code>string request_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique request ID to be presented by requestor at poll time - must not be transferred or displayed
       * </pre>
       *
       * <code>string request_id = 2;</code>
       * @param value The bytes for requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestId_ = value;
        onChanged();
        return this;
      }

      private int interval_ ;
      /**
       * <pre>
       * Refresh interval with which requestor should call PollAuthSessionStatus
       * </pre>
       *
       * <code>int32 interval = 3;</code>
       * @return The interval.
       */
      @java.lang.Override
      public int getInterval() {
        return interval_;
      }
      /**
       * <pre>
       * Refresh interval with which requestor should call PollAuthSessionStatus
       * </pre>
       *
       * <code>int32 interval = 3;</code>
       * @param value The interval to set.
       * @return This builder for chaining.
       */
      public Builder setInterval(int value) {
        
        interval_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Refresh interval with which requestor should call PollAuthSessionStatus
       * </pre>
       *
       * <code>int32 interval = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterval() {
        
        interval_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList allowedConfirmations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAllowedConfirmationsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          allowedConfirmations_ = new com.google.protobuf.LazyStringArrayList(allowedConfirmations_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * The confirmation types that will be able to confirm the request
       * </pre>
       *
       * <code>repeated string allowed_confirmations = 4;</code>
       * @return A list containing the allowedConfirmations.
       */
      public com.google.protobuf.ProtocolStringList
          getAllowedConfirmationsList() {
        return allowedConfirmations_.getUnmodifiableView();
      }
      /**
       * <pre>
       * The confirmation types that will be able to confirm the request
       * </pre>
       *
       * <code>repeated string allowed_confirmations = 4;</code>
       * @return The count of allowedConfirmations.
       */
      public int getAllowedConfirmationsCount() {
        return allowedConfirmations_.size();
      }
      /**
       * <pre>
       * The confirmation types that will be able to confirm the request
       * </pre>
       *
       * <code>repeated string allowed_confirmations = 4;</code>
       * @param index The index of the element to return.
       * @return The allowedConfirmations at the given index.
       */
      public java.lang.String getAllowedConfirmations(int index) {
        return allowedConfirmations_.get(index);
      }
      /**
       * <pre>
       * The confirmation types that will be able to confirm the request
       * </pre>
       *
       * <code>repeated string allowed_confirmations = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the allowedConfirmations at the given index.
       */
      public com.google.protobuf.ByteString
          getAllowedConfirmationsBytes(int index) {
        return allowedConfirmations_.getByteString(index);
      }
      /**
       * <pre>
       * The confirmation types that will be able to confirm the request
       * </pre>
       *
       * <code>repeated string allowed_confirmations = 4;</code>
       * @param index The index to set the value at.
       * @param value The allowedConfirmations to set.
       * @return This builder for chaining.
       */
      public Builder setAllowedConfirmations(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAllowedConfirmationsIsMutable();
        allowedConfirmations_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The confirmation types that will be able to confirm the request
       * </pre>
       *
       * <code>repeated string allowed_confirmations = 4;</code>
       * @param value The allowedConfirmations to add.
       * @return This builder for chaining.
       */
      public Builder addAllowedConfirmations(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAllowedConfirmationsIsMutable();
        allowedConfirmations_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The confirmation types that will be able to confirm the request
       * </pre>
       *
       * <code>repeated string allowed_confirmations = 4;</code>
       * @param values The allowedConfirmations to add.
       * @return This builder for chaining.
       */
      public Builder addAllAllowedConfirmations(
          java.lang.Iterable<java.lang.String> values) {
        ensureAllowedConfirmationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, allowedConfirmations_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The confirmation types that will be able to confirm the request
       * </pre>
       *
       * <code>repeated string allowed_confirmations = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAllowedConfirmations() {
        allowedConfirmations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The confirmation types that will be able to confirm the request
       * </pre>
       *
       * <code>repeated string allowed_confirmations = 4;</code>
       * @param value The bytes of the allowedConfirmations to add.
       * @return This builder for chaining.
       */
      public Builder addAllowedConfirmationsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAllowedConfirmationsIsMutable();
        allowedConfirmations_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object steamid_ = "";
      /**
       * <pre>
       * SteamID of the account logging in - will only be included if the credentials were correct
       * </pre>
       *
       * <code>string steamid = 5;</code>
       * @return The steamid.
       */
      public java.lang.String getSteamid() {
        java.lang.Object ref = steamid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          steamid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * SteamID of the account logging in - will only be included if the credentials were correct
       * </pre>
       *
       * <code>string steamid = 5;</code>
       * @return The bytes for steamid.
       */
      public com.google.protobuf.ByteString
          getSteamidBytes() {
        java.lang.Object ref = steamid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          steamid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * SteamID of the account logging in - will only be included if the credentials were correct
       * </pre>
       *
       * <code>string steamid = 5;</code>
       * @param value The steamid to set.
       * @return This builder for chaining.
       */
      public Builder setSteamid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        steamid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * SteamID of the account logging in - will only be included if the credentials were correct
       * </pre>
       *
       * <code>string steamid = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSteamid() {
        
        steamid_ = getDefaultInstance().getSteamid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * SteamID of the account logging in - will only be included if the credentials were correct
       * </pre>
       *
       * <code>string steamid = 5;</code>
       * @param value The bytes for steamid to set.
       * @return This builder for chaining.
       */
      public Builder setSteamidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        steamid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object weakToken_ = "";
      /**
       * <pre>
       * Partial-authentication token - limited lifetime and scope, included only if credentials were correct
       * </pre>
       *
       * <code>string weak_token = 6;</code>
       * @return The weakToken.
       */
      public java.lang.String getWeakToken() {
        java.lang.Object ref = weakToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          weakToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Partial-authentication token - limited lifetime and scope, included only if credentials were correct
       * </pre>
       *
       * <code>string weak_token = 6;</code>
       * @return The bytes for weakToken.
       */
      public com.google.protobuf.ByteString
          getWeakTokenBytes() {
        java.lang.Object ref = weakToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          weakToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Partial-authentication token - limited lifetime and scope, included only if credentials were correct
       * </pre>
       *
       * <code>string weak_token = 6;</code>
       * @param value The weakToken to set.
       * @return This builder for chaining.
       */
      public Builder setWeakToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weakToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Partial-authentication token - limited lifetime and scope, included only if credentials were correct
       * </pre>
       *
       * <code>string weak_token = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeakToken() {
        
        weakToken_ = getDefaultInstance().getWeakToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Partial-authentication token - limited lifetime and scope, included only if credentials were correct
       * </pre>
       *
       * <code>string weak_token = 6;</code>
       * @param value The bytes for weakToken to set.
       * @return This builder for chaining.
       */
      public Builder setWeakTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weakToken_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chenerzhu.crawler.proxy.protobufs.BeginAuthSessionViaCredentialsResponse)
    }

    // @@protoc_insertion_point(class_scope:com.chenerzhu.crawler.proxy.protobufs.BeginAuthSessionViaCredentialsResponse)
    private static final com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse();
    }

    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BeginAuthSessionViaCredentialsResponse>
        PARSER = new com.google.protobuf.AbstractParser<BeginAuthSessionViaCredentialsResponse>() {
      @java.lang.Override
      public BeginAuthSessionViaCredentialsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BeginAuthSessionViaCredentialsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BeginAuthSessionViaCredentialsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsResponse.BeginAuthSessionViaCredentialsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chenerzhu_crawler_proxy_protobufs_BeginAuthSessionViaCredentialsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chenerzhu_crawler_proxy_protobufs_BeginAuthSessionViaCredentialsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=CAuthentication_BeginAuthSessionViaCre" +
      "dentials_Response.proto\022%com.chenerzhu.c" +
      "rawler.proxy.protobufs\"\245\001\n&BeginAuthSess" +
      "ionViaCredentialsResponse\022\021\n\tclient_id\030\001" +
      " \001(\t\022\022\n\nrequest_id\030\002 \001(\t\022\020\n\010interval\030\003 \001" +
      "(\005\022\035\n\025allowed_confirmations\030\004 \003(\t\022\017\n\007ste" +
      "amid\030\005 \001(\t\022\022\n\nweak_token\030\006 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_chenerzhu_crawler_proxy_protobufs_BeginAuthSessionViaCredentialsResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chenerzhu_crawler_proxy_protobufs_BeginAuthSessionViaCredentialsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chenerzhu_crawler_proxy_protobufs_BeginAuthSessionViaCredentialsResponse_descriptor,
        new java.lang.String[] { "ClientId", "RequestId", "Interval", "AllowedConfirmations", "Steamid", "WeakToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
