// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CAuthentication_BeginAuthSessionViaCredentials_Request.proto

package com.chenerzhu.crawler.proxy.protobufs;

public final class CAuthenticationBeginAuthSessionViaCredentialsRequest {
  private CAuthenticationBeginAuthSessionViaCredentialsRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 平台类型的枚举
   * </pre>
   *
   * Protobuf enum {@code com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType}
   */
  public enum EAuthTokenPlatformType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 无效
     * </pre>
     *
     * <code>k_EAuthTokenPlatformType_Invalid = 0;</code>
     */
    k_EAuthTokenPlatformType_Invalid(0),
    /**
     * <pre>
     * 移动应用
     * </pre>
     *
     * <code>k_EAuthTokenPlatformType_MobileApp = 1;</code>
     */
    k_EAuthTokenPlatformType_MobileApp(1),
    /**
     * <pre>
     * 网络
     * </pre>
     *
     * <code>k_EAuthTokenPlatformType_Web = 2;</code>
     */
    k_EAuthTokenPlatformType_Web(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 无效
     * </pre>
     *
     * <code>k_EAuthTokenPlatformType_Invalid = 0;</code>
     */
    public static final int k_EAuthTokenPlatformType_Invalid_VALUE = 0;
    /**
     * <pre>
     * 移动应用
     * </pre>
     *
     * <code>k_EAuthTokenPlatformType_MobileApp = 1;</code>
     */
    public static final int k_EAuthTokenPlatformType_MobileApp_VALUE = 1;
    /**
     * <pre>
     * 网络
     * </pre>
     *
     * <code>k_EAuthTokenPlatformType_Web = 2;</code>
     */
    public static final int k_EAuthTokenPlatformType_Web_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EAuthTokenPlatformType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EAuthTokenPlatformType forNumber(int value) {
      switch (value) {
        case 0: return k_EAuthTokenPlatformType_Invalid;
        case 1: return k_EAuthTokenPlatformType_MobileApp;
        case 2: return k_EAuthTokenPlatformType_Web;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EAuthTokenPlatformType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EAuthTokenPlatformType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EAuthTokenPlatformType>() {
            public EAuthTokenPlatformType findValueByNumber(int number) {
              return EAuthTokenPlatformType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final EAuthTokenPlatformType[] VALUES = values();

    public static EAuthTokenPlatformType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EAuthTokenPlatformType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType)
  }

  /**
   * <pre>
   * 会话持久性的枚举类型
   * </pre>
   *
   * Protobuf enum {@code com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence}
   */
  public enum ESessionPersistence
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 无效
     * </pre>
     *
     * <code>k_ESessionPersistence_Invalid = 0;</code>
     */
    k_ESessionPersistence_Invalid(0),
    /**
     * <pre>
     * 持久会话
     * </pre>
     *
     * <code>k_ESessionPersistence_Persistent = 1;</code>
     */
    k_ESessionPersistence_Persistent(1),
    /**
     * <pre>
     * 短暂会话
     * </pre>
     *
     * <code>k_ESessionPersistence_Ephemeral = 2;</code>
     */
    k_ESessionPersistence_Ephemeral(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 无效
     * </pre>
     *
     * <code>k_ESessionPersistence_Invalid = 0;</code>
     */
    public static final int k_ESessionPersistence_Invalid_VALUE = 0;
    /**
     * <pre>
     * 持久会话
     * </pre>
     *
     * <code>k_ESessionPersistence_Persistent = 1;</code>
     */
    public static final int k_ESessionPersistence_Persistent_VALUE = 1;
    /**
     * <pre>
     * 短暂会话
     * </pre>
     *
     * <code>k_ESessionPersistence_Ephemeral = 2;</code>
     */
    public static final int k_ESessionPersistence_Ephemeral_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ESessionPersistence valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ESessionPersistence forNumber(int value) {
      switch (value) {
        case 0: return k_ESessionPersistence_Invalid;
        case 1: return k_ESessionPersistence_Persistent;
        case 2: return k_ESessionPersistence_Ephemeral;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ESessionPersistence>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ESessionPersistence> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ESessionPersistence>() {
            public ESessionPersistence findValueByNumber(int number) {
              return ESessionPersistence.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.getDescriptor().getEnumTypes().get(1);
    }

    private static final ESessionPersistence[] VALUES = values();

    public static ESessionPersistence valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ESessionPersistence(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence)
  }

  public interface CAuthentication_BeginAuthSessionViaCredentials_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 设备友好名称
     * </pre>
     *
     * <code>string device_friendly_name = 1;</code>
     * @return The deviceFriendlyName.
     */
    java.lang.String getDeviceFriendlyName();
    /**
     * <pre>
     * 设备友好名称
     * </pre>
     *
     * <code>string device_friendly_name = 1;</code>
     * @return The bytes for deviceFriendlyName.
     */
    com.google.protobuf.ByteString
        getDeviceFriendlyNameBytes();

    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string account_name = 2;</code>
     * @return The accountName.
     */
    java.lang.String getAccountName();
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string account_name = 2;</code>
     * @return The bytes for accountName.
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    /**
     * <pre>
     * RSA 加密的密码
     * </pre>
     *
     * <code>string encrypted_password = 3;</code>
     * @return The encryptedPassword.
     */
    java.lang.String getEncryptedPassword();
    /**
     * <pre>
     * RSA 加密的密码
     * </pre>
     *
     * <code>string encrypted_password = 3;</code>
     * @return The bytes for encryptedPassword.
     */
    com.google.protobuf.ByteString
        getEncryptedPasswordBytes();

    /**
     * <pre>
     * 是否记住登录信息
     * </pre>
     *
     * <code>bool remember_login = 4;</code>
     * @return The rememberLogin.
     */
    boolean getRememberLogin();

    /**
     * <pre>
     * 加密时间戳
     * </pre>
     *
     * <code>int64 encryption_timestamp = 5;</code>
     * @return The encryptionTimestamp.
     */
    long getEncryptionTimestamp();

    /**
     * <pre>
     * 平台类型
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 6;</code>
     * @return The enum numeric value on the wire for platformType.
     */
    int getPlatformTypeValue();
    /**
     * <pre>
     * 平台类型
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 6;</code>
     * @return The platformType.
     */
    com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.EAuthTokenPlatformType getPlatformType();

    /**
     * <pre>
     * 会话持久性
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
     * @return The enum numeric value on the wire for persistence.
     */
    int getPersistenceValue();
    /**
     * <pre>
     * 会话持久性
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
     * @return The persistence.
     */
    com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.ESessionPersistence getPersistence();

    /**
     * <pre>
     * 请求身份验证的客户端网站 ID
     * </pre>
     *
     * <code>string website_id = 8;</code>
     * @return The websiteId.
     */
    java.lang.String getWebsiteId();
    /**
     * <pre>
     * 请求身份验证的客户端网站 ID
     * </pre>
     *
     * <code>string website_id = 8;</code>
     * @return The bytes for websiteId.
     */
    com.google.protobuf.ByteString
        getWebsiteIdBytes();
  }
  /**
   * <pre>
   * 开始通过凭据进行身份验证的请求消息
   * </pre>
   *
   * Protobuf type {@code com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request}
   */
  public static final class CAuthentication_BeginAuthSessionViaCredentials_Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request)
      CAuthentication_BeginAuthSessionViaCredentials_RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CAuthentication_BeginAuthSessionViaCredentials_Request.newBuilder() to construct.
    private CAuthentication_BeginAuthSessionViaCredentials_Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CAuthentication_BeginAuthSessionViaCredentials_Request() {
      deviceFriendlyName_ = "";
      accountName_ = "";
      encryptedPassword_ = "";
      platformType_ = 0;
      persistence_ = 0;
      websiteId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CAuthentication_BeginAuthSessionViaCredentials_Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request.class, com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request.Builder.class);
    }

    public static final int DEVICE_FRIENDLY_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceFriendlyName_;
    /**
     * <pre>
     * 设备友好名称
     * </pre>
     *
     * <code>string device_friendly_name = 1;</code>
     * @return The deviceFriendlyName.
     */
    @java.lang.Override
    public java.lang.String getDeviceFriendlyName() {
      java.lang.Object ref = deviceFriendlyName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceFriendlyName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 设备友好名称
     * </pre>
     *
     * <code>string device_friendly_name = 1;</code>
     * @return The bytes for deviceFriendlyName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceFriendlyNameBytes() {
      java.lang.Object ref = deviceFriendlyName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceFriendlyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object accountName_;
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string account_name = 2;</code>
     * @return The accountName.
     */
    @java.lang.Override
    public java.lang.String getAccountName() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string account_name = 2;</code>
     * @return The bytes for accountName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPTED_PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object encryptedPassword_;
    /**
     * <pre>
     * RSA 加密的密码
     * </pre>
     *
     * <code>string encrypted_password = 3;</code>
     * @return The encryptedPassword.
     */
    @java.lang.Override
    public java.lang.String getEncryptedPassword() {
      java.lang.Object ref = encryptedPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        encryptedPassword_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * RSA 加密的密码
     * </pre>
     *
     * <code>string encrypted_password = 3;</code>
     * @return The bytes for encryptedPassword.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEncryptedPasswordBytes() {
      java.lang.Object ref = encryptedPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encryptedPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMEMBER_LOGIN_FIELD_NUMBER = 4;
    private boolean rememberLogin_;
    /**
     * <pre>
     * 是否记住登录信息
     * </pre>
     *
     * <code>bool remember_login = 4;</code>
     * @return The rememberLogin.
     */
    @java.lang.Override
    public boolean getRememberLogin() {
      return rememberLogin_;
    }

    public static final int ENCRYPTION_TIMESTAMP_FIELD_NUMBER = 5;
    private long encryptionTimestamp_;
    /**
     * <pre>
     * 加密时间戳
     * </pre>
     *
     * <code>int64 encryption_timestamp = 5;</code>
     * @return The encryptionTimestamp.
     */
    @java.lang.Override
    public long getEncryptionTimestamp() {
      return encryptionTimestamp_;
    }

    public static final int PLATFORM_TYPE_FIELD_NUMBER = 6;
    private int platformType_;
    /**
     * <pre>
     * 平台类型
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 6;</code>
     * @return The enum numeric value on the wire for platformType.
     */
    @java.lang.Override public int getPlatformTypeValue() {
      return platformType_;
    }
    /**
     * <pre>
     * 平台类型
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 6;</code>
     * @return The platformType.
     */
    @java.lang.Override public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.EAuthTokenPlatformType getPlatformType() {
      @SuppressWarnings("deprecation")
      com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.EAuthTokenPlatformType result = com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.EAuthTokenPlatformType.valueOf(platformType_);
      return result == null ? com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.EAuthTokenPlatformType.UNRECOGNIZED : result;
    }

    public static final int PERSISTENCE_FIELD_NUMBER = 7;
    private int persistence_;
    /**
     * <pre>
     * 会话持久性
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
     * @return The enum numeric value on the wire for persistence.
     */
    @java.lang.Override public int getPersistenceValue() {
      return persistence_;
    }
    /**
     * <pre>
     * 会话持久性
     * </pre>
     *
     * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
     * @return The persistence.
     */
    @java.lang.Override public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.ESessionPersistence getPersistence() {
      @SuppressWarnings("deprecation")
      com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.ESessionPersistence result = com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.ESessionPersistence.valueOf(persistence_);
      return result == null ? com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.ESessionPersistence.UNRECOGNIZED : result;
    }

    public static final int WEBSITE_ID_FIELD_NUMBER = 8;
    private volatile java.lang.Object websiteId_;
    /**
     * <pre>
     * 请求身份验证的客户端网站 ID
     * </pre>
     *
     * <code>string website_id = 8;</code>
     * @return The websiteId.
     */
    @java.lang.Override
    public java.lang.String getWebsiteId() {
      java.lang.Object ref = websiteId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        websiteId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求身份验证的客户端网站 ID
     * </pre>
     *
     * <code>string website_id = 8;</code>
     * @return The bytes for websiteId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWebsiteIdBytes() {
      java.lang.Object ref = websiteId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        websiteId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceFriendlyName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceFriendlyName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accountName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(encryptedPassword_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, encryptedPassword_);
      }
      if (rememberLogin_ != false) {
        output.writeBool(4, rememberLogin_);
      }
      if (encryptionTimestamp_ != 0L) {
        output.writeInt64(5, encryptionTimestamp_);
      }
      if (platformType_ != com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.EAuthTokenPlatformType.k_EAuthTokenPlatformType_Invalid.getNumber()) {
        output.writeEnum(6, platformType_);
      }
      if (persistence_ != com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.ESessionPersistence.k_ESessionPersistence_Invalid.getNumber()) {
        output.writeEnum(7, persistence_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(websiteId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, websiteId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceFriendlyName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceFriendlyName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accountName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(encryptedPassword_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, encryptedPassword_);
      }
      if (rememberLogin_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, rememberLogin_);
      }
      if (encryptionTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, encryptionTimestamp_);
      }
      if (platformType_ != com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.EAuthTokenPlatformType.k_EAuthTokenPlatformType_Invalid.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, platformType_);
      }
      if (persistence_ != com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.ESessionPersistence.k_ESessionPersistence_Invalid.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, persistence_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(websiteId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, websiteId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request)) {
        return super.equals(obj);
      }
      com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request other = (com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request) obj;

      if (!getDeviceFriendlyName()
          .equals(other.getDeviceFriendlyName())) return false;
      if (!getAccountName()
          .equals(other.getAccountName())) return false;
      if (!getEncryptedPassword()
          .equals(other.getEncryptedPassword())) return false;
      if (getRememberLogin()
          != other.getRememberLogin()) return false;
      if (getEncryptionTimestamp()
          != other.getEncryptionTimestamp()) return false;
      if (platformType_ != other.platformType_) return false;
      if (persistence_ != other.persistence_) return false;
      if (!getWebsiteId()
          .equals(other.getWebsiteId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_FRIENDLY_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceFriendlyName().hashCode();
      hash = (37 * hash) + ACCOUNT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getAccountName().hashCode();
      hash = (37 * hash) + ENCRYPTED_PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedPassword().hashCode();
      hash = (37 * hash) + REMEMBER_LOGIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRememberLogin());
      hash = (37 * hash) + ENCRYPTION_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEncryptionTimestamp());
      hash = (37 * hash) + PLATFORM_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + platformType_;
      hash = (37 * hash) + PERSISTENCE_FIELD_NUMBER;
      hash = (53 * hash) + persistence_;
      hash = (37 * hash) + WEBSITE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWebsiteId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 开始通过凭据进行身份验证的请求消息
     * </pre>
     *
     * Protobuf type {@code com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request)
        com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request.class, com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request.Builder.class);
      }

      // Construct using com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceFriendlyName_ = "";

        accountName_ = "";

        encryptedPassword_ = "";

        rememberLogin_ = false;

        encryptionTimestamp_ = 0L;

        platformType_ = 0;

        persistence_ = 0;

        websiteId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_descriptor;
      }

      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request getDefaultInstanceForType() {
        return com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request build() {
        com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request buildPartial() {
        com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request result = new com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request(this);
        result.deviceFriendlyName_ = deviceFriendlyName_;
        result.accountName_ = accountName_;
        result.encryptedPassword_ = encryptedPassword_;
        result.rememberLogin_ = rememberLogin_;
        result.encryptionTimestamp_ = encryptionTimestamp_;
        result.platformType_ = platformType_;
        result.persistence_ = persistence_;
        result.websiteId_ = websiteId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request) {
          return mergeFrom((com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request other) {
        if (other == com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request.getDefaultInstance()) return this;
        if (!other.getDeviceFriendlyName().isEmpty()) {
          deviceFriendlyName_ = other.deviceFriendlyName_;
          onChanged();
        }
        if (!other.getAccountName().isEmpty()) {
          accountName_ = other.accountName_;
          onChanged();
        }
        if (!other.getEncryptedPassword().isEmpty()) {
          encryptedPassword_ = other.encryptedPassword_;
          onChanged();
        }
        if (other.getRememberLogin() != false) {
          setRememberLogin(other.getRememberLogin());
        }
        if (other.getEncryptionTimestamp() != 0L) {
          setEncryptionTimestamp(other.getEncryptionTimestamp());
        }
        if (other.platformType_ != 0) {
          setPlatformTypeValue(other.getPlatformTypeValue());
        }
        if (other.persistence_ != 0) {
          setPersistenceValue(other.getPersistenceValue());
        }
        if (!other.getWebsiteId().isEmpty()) {
          websiteId_ = other.websiteId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                deviceFriendlyName_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                accountName_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                encryptedPassword_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 32: {
                rememberLogin_ = input.readBool();

                break;
              } // case 32
              case 40: {
                encryptionTimestamp_ = input.readInt64();

                break;
              } // case 40
              case 48: {
                platformType_ = input.readEnum();

                break;
              } // case 48
              case 56: {
                persistence_ = input.readEnum();

                break;
              } // case 56
              case 66: {
                websiteId_ = input.readStringRequireUtf8();

                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object deviceFriendlyName_ = "";
      /**
       * <pre>
       * 设备友好名称
       * </pre>
       *
       * <code>string device_friendly_name = 1;</code>
       * @return The deviceFriendlyName.
       */
      public java.lang.String getDeviceFriendlyName() {
        java.lang.Object ref = deviceFriendlyName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceFriendlyName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 设备友好名称
       * </pre>
       *
       * <code>string device_friendly_name = 1;</code>
       * @return The bytes for deviceFriendlyName.
       */
      public com.google.protobuf.ByteString
          getDeviceFriendlyNameBytes() {
        java.lang.Object ref = deviceFriendlyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceFriendlyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 设备友好名称
       * </pre>
       *
       * <code>string device_friendly_name = 1;</code>
       * @param value The deviceFriendlyName to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceFriendlyName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceFriendlyName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备友好名称
       * </pre>
       *
       * <code>string device_friendly_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceFriendlyName() {
        
        deviceFriendlyName_ = getDefaultInstance().getDeviceFriendlyName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备友好名称
       * </pre>
       *
       * <code>string device_friendly_name = 1;</code>
       * @param value The bytes for deviceFriendlyName to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceFriendlyNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceFriendlyName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object accountName_ = "";
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>string account_name = 2;</code>
       * @return The accountName.
       */
      public java.lang.String getAccountName() {
        java.lang.Object ref = accountName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>string account_name = 2;</code>
       * @return The bytes for accountName.
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        java.lang.Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>string account_name = 2;</code>
       * @param value The accountName to set.
       * @return This builder for chaining.
       */
      public Builder setAccountName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accountName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>string account_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountName() {
        
        accountName_ = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>string account_name = 2;</code>
       * @param value The bytes for accountName to set.
       * @return This builder for chaining.
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accountName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object encryptedPassword_ = "";
      /**
       * <pre>
       * RSA 加密的密码
       * </pre>
       *
       * <code>string encrypted_password = 3;</code>
       * @return The encryptedPassword.
       */
      public java.lang.String getEncryptedPassword() {
        java.lang.Object ref = encryptedPassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          encryptedPassword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * RSA 加密的密码
       * </pre>
       *
       * <code>string encrypted_password = 3;</code>
       * @return The bytes for encryptedPassword.
       */
      public com.google.protobuf.ByteString
          getEncryptedPasswordBytes() {
        java.lang.Object ref = encryptedPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          encryptedPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * RSA 加密的密码
       * </pre>
       *
       * <code>string encrypted_password = 3;</code>
       * @param value The encryptedPassword to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encryptedPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * RSA 加密的密码
       * </pre>
       *
       * <code>string encrypted_password = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptedPassword() {
        
        encryptedPassword_ = getDefaultInstance().getEncryptedPassword();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * RSA 加密的密码
       * </pre>
       *
       * <code>string encrypted_password = 3;</code>
       * @param value The bytes for encryptedPassword to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        encryptedPassword_ = value;
        onChanged();
        return this;
      }

      private boolean rememberLogin_ ;
      /**
       * <pre>
       * 是否记住登录信息
       * </pre>
       *
       * <code>bool remember_login = 4;</code>
       * @return The rememberLogin.
       */
      @java.lang.Override
      public boolean getRememberLogin() {
        return rememberLogin_;
      }
      /**
       * <pre>
       * 是否记住登录信息
       * </pre>
       *
       * <code>bool remember_login = 4;</code>
       * @param value The rememberLogin to set.
       * @return This builder for chaining.
       */
      public Builder setRememberLogin(boolean value) {
        
        rememberLogin_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否记住登录信息
       * </pre>
       *
       * <code>bool remember_login = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRememberLogin() {
        
        rememberLogin_ = false;
        onChanged();
        return this;
      }

      private long encryptionTimestamp_ ;
      /**
       * <pre>
       * 加密时间戳
       * </pre>
       *
       * <code>int64 encryption_timestamp = 5;</code>
       * @return The encryptionTimestamp.
       */
      @java.lang.Override
      public long getEncryptionTimestamp() {
        return encryptionTimestamp_;
      }
      /**
       * <pre>
       * 加密时间戳
       * </pre>
       *
       * <code>int64 encryption_timestamp = 5;</code>
       * @param value The encryptionTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptionTimestamp(long value) {
        
        encryptionTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 加密时间戳
       * </pre>
       *
       * <code>int64 encryption_timestamp = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptionTimestamp() {
        
        encryptionTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private int platformType_ = 0;
      /**
       * <pre>
       * 平台类型
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 6;</code>
       * @return The enum numeric value on the wire for platformType.
       */
      @java.lang.Override public int getPlatformTypeValue() {
        return platformType_;
      }
      /**
       * <pre>
       * 平台类型
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 6;</code>
       * @param value The enum numeric value on the wire for platformType to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformTypeValue(int value) {
        
        platformType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 平台类型
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 6;</code>
       * @return The platformType.
       */
      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.EAuthTokenPlatformType getPlatformType() {
        @SuppressWarnings("deprecation")
        com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.EAuthTokenPlatformType result = com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.EAuthTokenPlatformType.valueOf(platformType_);
        return result == null ? com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.EAuthTokenPlatformType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 平台类型
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 6;</code>
       * @param value The platformType to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformType(com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.EAuthTokenPlatformType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        platformType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 平台类型
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.EAuthTokenPlatformType platform_type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlatformType() {
        
        platformType_ = 0;
        onChanged();
        return this;
      }

      private int persistence_ = 0;
      /**
       * <pre>
       * 会话持久性
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
       * @return The enum numeric value on the wire for persistence.
       */
      @java.lang.Override public int getPersistenceValue() {
        return persistence_;
      }
      /**
       * <pre>
       * 会话持久性
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
       * @param value The enum numeric value on the wire for persistence to set.
       * @return This builder for chaining.
       */
      public Builder setPersistenceValue(int value) {
        
        persistence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 会话持久性
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
       * @return The persistence.
       */
      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.ESessionPersistence getPersistence() {
        @SuppressWarnings("deprecation")
        com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.ESessionPersistence result = com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.ESessionPersistence.valueOf(persistence_);
        return result == null ? com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.ESessionPersistence.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 会话持久性
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
       * @param value The persistence to set.
       * @return This builder for chaining.
       */
      public Builder setPersistence(com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.ESessionPersistence value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        persistence_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 会话持久性
       * </pre>
       *
       * <code>.com.chenerzhu.crawler.proxy.protobufs.ESessionPersistence persistence = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPersistence() {
        
        persistence_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object websiteId_ = "";
      /**
       * <pre>
       * 请求身份验证的客户端网站 ID
       * </pre>
       *
       * <code>string website_id = 8;</code>
       * @return The websiteId.
       */
      public java.lang.String getWebsiteId() {
        java.lang.Object ref = websiteId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          websiteId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求身份验证的客户端网站 ID
       * </pre>
       *
       * <code>string website_id = 8;</code>
       * @return The bytes for websiteId.
       */
      public com.google.protobuf.ByteString
          getWebsiteIdBytes() {
        java.lang.Object ref = websiteId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          websiteId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求身份验证的客户端网站 ID
       * </pre>
       *
       * <code>string website_id = 8;</code>
       * @param value The websiteId to set.
       * @return This builder for chaining.
       */
      public Builder setWebsiteId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        websiteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求身份验证的客户端网站 ID
       * </pre>
       *
       * <code>string website_id = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearWebsiteId() {
        
        websiteId_ = getDefaultInstance().getWebsiteId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求身份验证的客户端网站 ID
       * </pre>
       *
       * <code>string website_id = 8;</code>
       * @param value The bytes for websiteId to set.
       * @return This builder for chaining.
       */
      public Builder setWebsiteIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        websiteId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request)
    }

    // @@protoc_insertion_point(class_scope:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_BeginAuthSessionViaCredentials_Request)
    private static final com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request();
    }

    public static com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CAuthentication_BeginAuthSessionViaCredentials_Request>
        PARSER = new com.google.protobuf.AbstractParser<CAuthentication_BeginAuthSessionViaCredentials_Request>() {
      @java.lang.Override
      public CAuthentication_BeginAuthSessionViaCredentials_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CAuthentication_BeginAuthSessionViaCredentials_Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CAuthentication_BeginAuthSessionViaCredentials_Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chenerzhu.crawler.proxy.protobufs.CAuthenticationBeginAuthSessionViaCredentialsRequest.CAuthentication_BeginAuthSessionViaCredentials_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<CAuthentication_BeginAuthSessionViaCre" +
      "dentials_Request.proto\022%com.chenerzhu.cr" +
      "awler.proxy.protobufs\"\371\002\n6CAuthenticatio" +
      "n_BeginAuthSessionViaCredentials_Request" +
      "\022\034\n\024device_friendly_name\030\001 \001(\t\022\024\n\014accoun" +
      "t_name\030\002 \001(\t\022\032\n\022encrypted_password\030\003 \001(\t" +
      "\022\026\n\016remember_login\030\004 \001(\010\022\034\n\024encryption_t" +
      "imestamp\030\005 \001(\003\022T\n\rplatform_type\030\006 \001(\0162=." +
      "com.chenerzhu.crawler.proxy.protobufs.EA" +
      "uthTokenPlatformType\022O\n\013persistence\030\007 \001(" +
      "\0162:.com.chenerzhu.crawler.proxy.protobuf" +
      "s.ESessionPersistence\022\022\n\nwebsite_id\030\010 \001(" +
      "\t*\210\001\n\026EAuthTokenPlatformType\022$\n k_EAuthT" +
      "okenPlatformType_Invalid\020\000\022&\n\"k_EAuthTok" +
      "enPlatformType_MobileApp\020\001\022 \n\034k_EAuthTok" +
      "enPlatformType_Web\020\002*\203\001\n\023ESessionPersist" +
      "ence\022!\n\035k_ESessionPersistence_Invalid\020\000\022" +
      "$\n k_ESessionPersistence_Persistent\020\001\022#\n" +
      "\037k_ESessionPersistence_Ephemeral\020\002b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_BeginAuthSessionViaCredentials_Request_descriptor,
        new java.lang.String[] { "DeviceFriendlyName", "AccountName", "EncryptedPassword", "RememberLogin", "EncryptionTimestamp", "PlatformType", "Persistence", "WebsiteId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
