// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CAuthentication_GetPasswordRSAPublicKey_Response.proto

package com.chenerzhu.crawler.proxy.protobufs;

public final class CAuthenticationGetPasswordRSAPublicKeyResponse {
  private CAuthenticationGetPasswordRSAPublicKeyResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CAuthentication_GetPasswordRSAPublicKey_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_GetPasswordRSAPublicKey_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 定义任何需要的字段，比如请求 ID，或者请求的上下文等
     * </pre>
     *
     * <code>string publickey_mod = 1;</code>
     * @return The publickeyMod.
     */
    String getPublickeyMod();
    /**
     * <pre>
     * 定义任何需要的字段，比如请求 ID，或者请求的上下文等
     * </pre>
     *
     * <code>string publickey_mod = 1;</code>
     * @return The bytes for publickeyMod.
     */
    com.google.protobuf.ByteString
        getPublickeyModBytes();

    /**
     * <code>string publickey_exp = 2;</code>
     * @return The publickeyExp.
     */
    String getPublickeyExp();
    /**
     * <code>string publickey_exp = 2;</code>
     * @return The bytes for publickeyExp.
     */
    com.google.protobuf.ByteString
        getPublickeyExpBytes();

    /**
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code com.chenerzhu.crawler.proxy.protobufs.CAuthentication_GetPasswordRSAPublicKey_Response}
   */
  public static final class CAuthentication_GetPasswordRSAPublicKey_Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_GetPasswordRSAPublicKey_Response)
      CAuthentication_GetPasswordRSAPublicKey_ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CAuthentication_GetPasswordRSAPublicKey_Response.newBuilder() to construct.
    private CAuthentication_GetPasswordRSAPublicKey_Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CAuthentication_GetPasswordRSAPublicKey_Response() {
      publickeyMod_ = "";
      publickeyExp_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CAuthentication_GetPasswordRSAPublicKey_Response();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CAuthenticationGetPasswordRSAPublicKeyResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_GetPasswordRSAPublicKey_Response_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CAuthenticationGetPasswordRSAPublicKeyResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_GetPasswordRSAPublicKey_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CAuthentication_GetPasswordRSAPublicKey_Response.class, Builder.class);
    }

    public static final int PUBLICKEY_MOD_FIELD_NUMBER = 1;
    private volatile Object publickeyMod_;
    /**
     * <pre>
     * 定义任何需要的字段，比如请求 ID，或者请求的上下文等
     * </pre>
     *
     * <code>string publickey_mod = 1;</code>
     * @return The publickeyMod.
     */
    @Override
    public String getPublickeyMod() {
      Object ref = publickeyMod_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        publickeyMod_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 定义任何需要的字段，比如请求 ID，或者请求的上下文等
     * </pre>
     *
     * <code>string publickey_mod = 1;</code>
     * @return The bytes for publickeyMod.
     */
    @Override
    public com.google.protobuf.ByteString
        getPublickeyModBytes() {
      Object ref = publickeyMod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        publickeyMod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBLICKEY_EXP_FIELD_NUMBER = 2;
    private volatile Object publickeyExp_;
    /**
     * <code>string publickey_exp = 2;</code>
     * @return The publickeyExp.
     */
    @Override
    public String getPublickeyExp() {
      Object ref = publickeyExp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        publickeyExp_ = s;
        return s;
      }
    }
    /**
     * <code>string publickey_exp = 2;</code>
     * @return The bytes for publickeyExp.
     */
    @Override
    public com.google.protobuf.ByteString
        getPublickeyExpBytes() {
      Object ref = publickeyExp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        publickeyExp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(publickeyMod_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, publickeyMod_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(publickeyExp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, publickeyExp_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(3, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(publickeyMod_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, publickeyMod_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(publickeyExp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, publickeyExp_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CAuthentication_GetPasswordRSAPublicKey_Response)) {
        return super.equals(obj);
      }
      CAuthentication_GetPasswordRSAPublicKey_Response other = (CAuthentication_GetPasswordRSAPublicKey_Response) obj;

      if (!getPublickeyMod()
          .equals(other.getPublickeyMod())) return false;
      if (!getPublickeyExp()
          .equals(other.getPublickeyExp())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PUBLICKEY_MOD_FIELD_NUMBER;
      hash = (53 * hash) + getPublickeyMod().hashCode();
      hash = (37 * hash) + PUBLICKEY_EXP_FIELD_NUMBER;
      hash = (53 * hash) + getPublickeyExp().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CAuthentication_GetPasswordRSAPublicKey_Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CAuthentication_GetPasswordRSAPublicKey_Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CAuthentication_GetPasswordRSAPublicKey_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CAuthentication_GetPasswordRSAPublicKey_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CAuthentication_GetPasswordRSAPublicKey_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CAuthentication_GetPasswordRSAPublicKey_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CAuthentication_GetPasswordRSAPublicKey_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CAuthentication_GetPasswordRSAPublicKey_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CAuthentication_GetPasswordRSAPublicKey_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CAuthentication_GetPasswordRSAPublicKey_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CAuthentication_GetPasswordRSAPublicKey_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CAuthentication_GetPasswordRSAPublicKey_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CAuthentication_GetPasswordRSAPublicKey_Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.chenerzhu.crawler.proxy.protobufs.CAuthentication_GetPasswordRSAPublicKey_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_GetPasswordRSAPublicKey_Response)
        CAuthentication_GetPasswordRSAPublicKey_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CAuthenticationGetPasswordRSAPublicKeyResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_GetPasswordRSAPublicKey_Response_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CAuthenticationGetPasswordRSAPublicKeyResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_GetPasswordRSAPublicKey_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CAuthentication_GetPasswordRSAPublicKey_Response.class, Builder.class);
      }

      // Construct using com.chenerzhu.crawler.proxy.protobufs.CAuthenticationGetPasswordRSAPublicKeyResponse.CAuthentication_GetPasswordRSAPublicKey_Response.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        publickeyMod_ = "";

        publickeyExp_ = "";

        timestamp_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CAuthenticationGetPasswordRSAPublicKeyResponse.internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_GetPasswordRSAPublicKey_Response_descriptor;
      }

      @Override
      public CAuthentication_GetPasswordRSAPublicKey_Response getDefaultInstanceForType() {
        return CAuthentication_GetPasswordRSAPublicKey_Response.getDefaultInstance();
      }

      @Override
      public CAuthentication_GetPasswordRSAPublicKey_Response build() {
        CAuthentication_GetPasswordRSAPublicKey_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CAuthentication_GetPasswordRSAPublicKey_Response buildPartial() {
        CAuthentication_GetPasswordRSAPublicKey_Response result = new CAuthentication_GetPasswordRSAPublicKey_Response(this);
        result.publickeyMod_ = publickeyMod_;
        result.publickeyExp_ = publickeyExp_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CAuthentication_GetPasswordRSAPublicKey_Response) {
          return mergeFrom((CAuthentication_GetPasswordRSAPublicKey_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CAuthentication_GetPasswordRSAPublicKey_Response other) {
        if (other == CAuthentication_GetPasswordRSAPublicKey_Response.getDefaultInstance()) return this;
        if (!other.getPublickeyMod().isEmpty()) {
          publickeyMod_ = other.publickeyMod_;
          onChanged();
        }
        if (!other.getPublickeyExp().isEmpty()) {
          publickeyExp_ = other.publickeyExp_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                publickeyMod_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                publickeyExp_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 24: {
                timestamp_ = input.readInt64();

                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private Object publickeyMod_ = "";
      /**
       * <pre>
       * 定义任何需要的字段，比如请求 ID，或者请求的上下文等
       * </pre>
       *
       * <code>string publickey_mod = 1;</code>
       * @return The publickeyMod.
       */
      public String getPublickeyMod() {
        Object ref = publickeyMod_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          publickeyMod_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 定义任何需要的字段，比如请求 ID，或者请求的上下文等
       * </pre>
       *
       * <code>string publickey_mod = 1;</code>
       * @return The bytes for publickeyMod.
       */
      public com.google.protobuf.ByteString
          getPublickeyModBytes() {
        Object ref = publickeyMod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          publickeyMod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 定义任何需要的字段，比如请求 ID，或者请求的上下文等
       * </pre>
       *
       * <code>string publickey_mod = 1;</code>
       * @param value The publickeyMod to set.
       * @return This builder for chaining.
       */
      public Builder setPublickeyMod(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publickeyMod_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 定义任何需要的字段，比如请求 ID，或者请求的上下文等
       * </pre>
       *
       * <code>string publickey_mod = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublickeyMod() {
        
        publickeyMod_ = getDefaultInstance().getPublickeyMod();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 定义任何需要的字段，比如请求 ID，或者请求的上下文等
       * </pre>
       *
       * <code>string publickey_mod = 1;</code>
       * @param value The bytes for publickeyMod to set.
       * @return This builder for chaining.
       */
      public Builder setPublickeyModBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        publickeyMod_ = value;
        onChanged();
        return this;
      }

      private Object publickeyExp_ = "";
      /**
       * <code>string publickey_exp = 2;</code>
       * @return The publickeyExp.
       */
      public String getPublickeyExp() {
        Object ref = publickeyExp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          publickeyExp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string publickey_exp = 2;</code>
       * @return The bytes for publickeyExp.
       */
      public com.google.protobuf.ByteString
          getPublickeyExpBytes() {
        Object ref = publickeyExp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          publickeyExp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string publickey_exp = 2;</code>
       * @param value The publickeyExp to set.
       * @return This builder for chaining.
       */
      public Builder setPublickeyExp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publickeyExp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string publickey_exp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublickeyExp() {
        
        publickeyExp_ = getDefaultInstance().getPublickeyExp();
        onChanged();
        return this;
      }
      /**
       * <code>string publickey_exp = 2;</code>
       * @param value The bytes for publickeyExp to set.
       * @return This builder for chaining.
       */
      public Builder setPublickeyExpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        publickeyExp_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 3;</code>
       * @return The timestamp.
       */
      @Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_GetPasswordRSAPublicKey_Response)
    }

    // @@protoc_insertion_point(class_scope:com.chenerzhu.crawler.proxy.protobufs.CAuthentication_GetPasswordRSAPublicKey_Response)
    private static final CAuthentication_GetPasswordRSAPublicKey_Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CAuthentication_GetPasswordRSAPublicKey_Response();
    }

    public static CAuthentication_GetPasswordRSAPublicKey_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CAuthentication_GetPasswordRSAPublicKey_Response>
        PARSER = new com.google.protobuf.AbstractParser<CAuthentication_GetPasswordRSAPublicKey_Response>() {
      @Override
      public CAuthentication_GetPasswordRSAPublicKey_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CAuthentication_GetPasswordRSAPublicKey_Response> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CAuthentication_GetPasswordRSAPublicKey_Response> getParserForType() {
      return PARSER;
    }

    @Override
    public CAuthentication_GetPasswordRSAPublicKey_Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_GetPasswordRSAPublicKey_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_GetPasswordRSAPublicKey_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n6CAuthentication_GetPasswordRSAPublicKe" +
      "y_Response.proto\022%com.chenerzhu.crawler." +
      "proxy.protobufs\"s\n0CAuthentication_GetPa" +
      "sswordRSAPublicKey_Response\022\025\n\rpublickey" +
      "_mod\030\001 \001(\t\022\025\n\rpublickey_exp\030\002 \001(\t\022\021\n\ttim" +
      "estamp\030\003 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_GetPasswordRSAPublicKey_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_GetPasswordRSAPublicKey_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chenerzhu_crawler_proxy_protobufs_CAuthentication_GetPasswordRSAPublicKey_Response_descriptor,
        new String[] { "PublickeyMod", "PublickeyExp", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
