// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums_pb2.proto

package com.chenerzhu.crawler.proxy.protobufs;

public final class EnumsPb2 {
  private EnumsPb2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 发布文件查询类型
   * </pre>
   *
   * Protobuf enum {@code com.chenerzhu.crawler.proxy.protobufs.EPublishedFileQueryType}
   */
  public enum EPublishedFileQueryType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_PublishedFileQueryType_RankedByVote = 0;</code>
     */
    k_PublishedFileQueryType_RankedByVote(0),
    /**
     * <code>k_PublishedFileQueryType_RankedByPublicationDate = 1;</code>
     */
    k_PublishedFileQueryType_RankedByPublicationDate(1),
    /**
     * <code>k_PublishedFileQueryType_AcceptedForGameRankedByAcceptanceDate = 2;</code>
     */
    k_PublishedFileQueryType_AcceptedForGameRankedByAcceptanceDate(2),
    /**
     * <code>k_PublishedFileQueryType_RankedByTrend = 3;</code>
     */
    k_PublishedFileQueryType_RankedByTrend(3),
    /**
     * <code>k_PublishedFileQueryType_FavoritedByFriendsRankedByPublicationDate = 4;</code>
     */
    k_PublishedFileQueryType_FavoritedByFriendsRankedByPublicationDate(4),
    /**
     * <code>k_PublishedFileQueryType_CreatedByFriendsRankedByPublicationDate = 5;</code>
     */
    k_PublishedFileQueryType_CreatedByFriendsRankedByPublicationDate(5),
    /**
     * <code>k_PublishedFileQueryType_RankedByNumTimesReported = 6;</code>
     */
    k_PublishedFileQueryType_RankedByNumTimesReported(6),
    /**
     * <code>k_PublishedFileQueryType_CreatedByFollowedUsersRankedByPublicationDate = 7;</code>
     */
    k_PublishedFileQueryType_CreatedByFollowedUsersRankedByPublicationDate(7),
    /**
     * <code>k_PublishedFileQueryType_NotYetRated = 8;</code>
     */
    k_PublishedFileQueryType_NotYetRated(8),
    /**
     * <code>k_PublishedFileQueryType_RankedByTotalUniqueSubscriptions = 9;</code>
     */
    k_PublishedFileQueryType_RankedByTotalUniqueSubscriptions(9),
    /**
     * <code>k_PublishedFileQueryType_RankedByTotalVotesAsc = 10;</code>
     */
    k_PublishedFileQueryType_RankedByTotalVotesAsc(10),
    /**
     * <code>k_PublishedFileQueryType_RankedByVotesUp = 11;</code>
     */
    k_PublishedFileQueryType_RankedByVotesUp(11),
    /**
     * <code>k_PublishedFileQueryType_RankedByTextSearch = 12;</code>
     */
    k_PublishedFileQueryType_RankedByTextSearch(12),
    /**
     * <code>k_PublishedFileQueryType_RankedByPlaytimeTrend = 13;</code>
     */
    k_PublishedFileQueryType_RankedByPlaytimeTrend(13),
    /**
     * <code>k_PublishedFileQueryType_RankedByTotalPlaytime = 14;</code>
     */
    k_PublishedFileQueryType_RankedByTotalPlaytime(14),
    /**
     * <code>k_PublishedFileQueryType_RankedByAveragePlaytimeTrend = 15;</code>
     */
    k_PublishedFileQueryType_RankedByAveragePlaytimeTrend(15),
    /**
     * <code>k_PublishedFileQueryType_RankedByLifetimeAveragePlaytime = 16;</code>
     */
    k_PublishedFileQueryType_RankedByLifetimeAveragePlaytime(16),
    /**
     * <code>k_PublishedFileQueryType_RankedByPlaytimeSessionsTrend = 17;</code>
     */
    k_PublishedFileQueryType_RankedByPlaytimeSessionsTrend(17),
    /**
     * <code>k_PublishedFileQueryType_RankedByLifetimePlaytimeSessions = 18;</code>
     */
    k_PublishedFileQueryType_RankedByLifetimePlaytimeSessions(18),
    /**
     * <code>k_PublishedFileQueryType_RankedByInappropriateContentRating = 19;</code>
     */
    k_PublishedFileQueryType_RankedByInappropriateContentRating(19),
    /**
     * <code>k_PublishedFileQueryType_RankedByBanContentCheck = 20;</code>
     */
    k_PublishedFileQueryType_RankedByBanContentCheck(20),
    /**
     * <code>k_PublishedFileQueryType_RankedByLastUpdatedDate = 21;</code>
     */
    k_PublishedFileQueryType_RankedByLastUpdatedDate(21),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>k_PublishedFileQueryType_RankedByVote = 0;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByVote_VALUE = 0;
    /**
     * <code>k_PublishedFileQueryType_RankedByPublicationDate = 1;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByPublicationDate_VALUE = 1;
    /**
     * <code>k_PublishedFileQueryType_AcceptedForGameRankedByAcceptanceDate = 2;</code>
     */
    public static final int k_PublishedFileQueryType_AcceptedForGameRankedByAcceptanceDate_VALUE = 2;
    /**
     * <code>k_PublishedFileQueryType_RankedByTrend = 3;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByTrend_VALUE = 3;
    /**
     * <code>k_PublishedFileQueryType_FavoritedByFriendsRankedByPublicationDate = 4;</code>
     */
    public static final int k_PublishedFileQueryType_FavoritedByFriendsRankedByPublicationDate_VALUE = 4;
    /**
     * <code>k_PublishedFileQueryType_CreatedByFriendsRankedByPublicationDate = 5;</code>
     */
    public static final int k_PublishedFileQueryType_CreatedByFriendsRankedByPublicationDate_VALUE = 5;
    /**
     * <code>k_PublishedFileQueryType_RankedByNumTimesReported = 6;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByNumTimesReported_VALUE = 6;
    /**
     * <code>k_PublishedFileQueryType_CreatedByFollowedUsersRankedByPublicationDate = 7;</code>
     */
    public static final int k_PublishedFileQueryType_CreatedByFollowedUsersRankedByPublicationDate_VALUE = 7;
    /**
     * <code>k_PublishedFileQueryType_NotYetRated = 8;</code>
     */
    public static final int k_PublishedFileQueryType_NotYetRated_VALUE = 8;
    /**
     * <code>k_PublishedFileQueryType_RankedByTotalUniqueSubscriptions = 9;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByTotalUniqueSubscriptions_VALUE = 9;
    /**
     * <code>k_PublishedFileQueryType_RankedByTotalVotesAsc = 10;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByTotalVotesAsc_VALUE = 10;
    /**
     * <code>k_PublishedFileQueryType_RankedByVotesUp = 11;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByVotesUp_VALUE = 11;
    /**
     * <code>k_PublishedFileQueryType_RankedByTextSearch = 12;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByTextSearch_VALUE = 12;
    /**
     * <code>k_PublishedFileQueryType_RankedByPlaytimeTrend = 13;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByPlaytimeTrend_VALUE = 13;
    /**
     * <code>k_PublishedFileQueryType_RankedByTotalPlaytime = 14;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByTotalPlaytime_VALUE = 14;
    /**
     * <code>k_PublishedFileQueryType_RankedByAveragePlaytimeTrend = 15;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByAveragePlaytimeTrend_VALUE = 15;
    /**
     * <code>k_PublishedFileQueryType_RankedByLifetimeAveragePlaytime = 16;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByLifetimeAveragePlaytime_VALUE = 16;
    /**
     * <code>k_PublishedFileQueryType_RankedByPlaytimeSessionsTrend = 17;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByPlaytimeSessionsTrend_VALUE = 17;
    /**
     * <code>k_PublishedFileQueryType_RankedByLifetimePlaytimeSessions = 18;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByLifetimePlaytimeSessions_VALUE = 18;
    /**
     * <code>k_PublishedFileQueryType_RankedByInappropriateContentRating = 19;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByInappropriateContentRating_VALUE = 19;
    /**
     * <code>k_PublishedFileQueryType_RankedByBanContentCheck = 20;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByBanContentCheck_VALUE = 20;
    /**
     * <code>k_PublishedFileQueryType_RankedByLastUpdatedDate = 21;</code>
     */
    public static final int k_PublishedFileQueryType_RankedByLastUpdatedDate_VALUE = 21;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EPublishedFileQueryType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EPublishedFileQueryType forNumber(int value) {
      switch (value) {
        case 0: return k_PublishedFileQueryType_RankedByVote;
        case 1: return k_PublishedFileQueryType_RankedByPublicationDate;
        case 2: return k_PublishedFileQueryType_AcceptedForGameRankedByAcceptanceDate;
        case 3: return k_PublishedFileQueryType_RankedByTrend;
        case 4: return k_PublishedFileQueryType_FavoritedByFriendsRankedByPublicationDate;
        case 5: return k_PublishedFileQueryType_CreatedByFriendsRankedByPublicationDate;
        case 6: return k_PublishedFileQueryType_RankedByNumTimesReported;
        case 7: return k_PublishedFileQueryType_CreatedByFollowedUsersRankedByPublicationDate;
        case 8: return k_PublishedFileQueryType_NotYetRated;
        case 9: return k_PublishedFileQueryType_RankedByTotalUniqueSubscriptions;
        case 10: return k_PublishedFileQueryType_RankedByTotalVotesAsc;
        case 11: return k_PublishedFileQueryType_RankedByVotesUp;
        case 12: return k_PublishedFileQueryType_RankedByTextSearch;
        case 13: return k_PublishedFileQueryType_RankedByPlaytimeTrend;
        case 14: return k_PublishedFileQueryType_RankedByTotalPlaytime;
        case 15: return k_PublishedFileQueryType_RankedByAveragePlaytimeTrend;
        case 16: return k_PublishedFileQueryType_RankedByLifetimeAveragePlaytime;
        case 17: return k_PublishedFileQueryType_RankedByPlaytimeSessionsTrend;
        case 18: return k_PublishedFileQueryType_RankedByLifetimePlaytimeSessions;
        case 19: return k_PublishedFileQueryType_RankedByInappropriateContentRating;
        case 20: return k_PublishedFileQueryType_RankedByBanContentCheck;
        case 21: return k_PublishedFileQueryType_RankedByLastUpdatedDate;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EPublishedFileQueryType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EPublishedFileQueryType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EPublishedFileQueryType>() {
            public EPublishedFileQueryType findValueByNumber(int number) {
              return EPublishedFileQueryType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.getDescriptor().getEnumTypes().get(0);
    }

    private static final EPublishedFileQueryType[] VALUES = values();

    public static EPublishedFileQueryType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EPublishedFileQueryType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.chenerzhu.crawler.proxy.protobufs.EPublishedFileQueryType)
  }

  /**
   * <pre>
   * 不当内容提供者
   * </pre>
   *
   * Protobuf enum {@code com.chenerzhu.crawler.proxy.protobufs.EPublishedFileInappropriateProvider}
   */
  public enum EPublishedFileInappropriateProvider
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_EPublishedFileInappropriateProvider_Invalid = 0;</code>
     */
    k_EPublishedFileInappropriateProvider_Invalid(0),
    /**
     * <code>k_EPublishedFileInappropriateProvider_Google = 1;</code>
     */
    k_EPublishedFileInappropriateProvider_Google(1),
    /**
     * <code>k_EPublishedFileInappropriateProvider_Amazon = 2;</code>
     */
    k_EPublishedFileInappropriateProvider_Amazon(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>k_EPublishedFileInappropriateProvider_Invalid = 0;</code>
     */
    public static final int k_EPublishedFileInappropriateProvider_Invalid_VALUE = 0;
    /**
     * <code>k_EPublishedFileInappropriateProvider_Google = 1;</code>
     */
    public static final int k_EPublishedFileInappropriateProvider_Google_VALUE = 1;
    /**
     * <code>k_EPublishedFileInappropriateProvider_Amazon = 2;</code>
     */
    public static final int k_EPublishedFileInappropriateProvider_Amazon_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EPublishedFileInappropriateProvider valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EPublishedFileInappropriateProvider forNumber(int value) {
      switch (value) {
        case 0: return k_EPublishedFileInappropriateProvider_Invalid;
        case 1: return k_EPublishedFileInappropriateProvider_Google;
        case 2: return k_EPublishedFileInappropriateProvider_Amazon;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EPublishedFileInappropriateProvider>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EPublishedFileInappropriateProvider> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EPublishedFileInappropriateProvider>() {
            public EPublishedFileInappropriateProvider findValueByNumber(int number) {
              return EPublishedFileInappropriateProvider.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.getDescriptor().getEnumTypes().get(1);
    }

    private static final EPublishedFileInappropriateProvider[] VALUES = values();

    public static EPublishedFileInappropriateProvider valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EPublishedFileInappropriateProvider(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.chenerzhu.crawler.proxy.protobufs.EPublishedFileInappropriateProvider)
  }

  /**
   * <pre>
   * 不当内容结果
   * </pre>
   *
   * Protobuf enum {@code com.chenerzhu.crawler.proxy.protobufs.EPublishedFileInappropriateResult}
   */
  public enum EPublishedFileInappropriateResult
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_EPublishedFileInappropriateResult_NotScanned = 0;</code>
     */
    k_EPublishedFileInappropriateResult_NotScanned(0),
    /**
     * <code>k_EPublishedFileInappropriateResult_VeryUnlikely = 1;</code>
     */
    k_EPublishedFileInappropriateResult_VeryUnlikely(1),
    /**
     * <code>k_EPublishedFileInappropriateResult_Unlikely = 2;</code>
     */
    k_EPublishedFileInappropriateResult_Unlikely(2),
    /**
     * <code>k_EPublishedFileInappropriateResult_Possible = 3;</code>
     */
    k_EPublishedFileInappropriateResult_Possible(3),
    /**
     * <code>k_EPublishedFileInappropriateResult_Likely = 4;</code>
     */
    k_EPublishedFileInappropriateResult_Likely(4),
    /**
     * <code>k_EPublishedFileInappropriateResult_VeryLikely = 5;</code>
     */
    k_EPublishedFileInappropriateResult_VeryLikely(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>k_EPublishedFileInappropriateResult_NotScanned = 0;</code>
     */
    public static final int k_EPublishedFileInappropriateResult_NotScanned_VALUE = 0;
    /**
     * <code>k_EPublishedFileInappropriateResult_VeryUnlikely = 1;</code>
     */
    public static final int k_EPublishedFileInappropriateResult_VeryUnlikely_VALUE = 1;
    /**
     * <code>k_EPublishedFileInappropriateResult_Unlikely = 2;</code>
     */
    public static final int k_EPublishedFileInappropriateResult_Unlikely_VALUE = 2;
    /**
     * <code>k_EPublishedFileInappropriateResult_Possible = 3;</code>
     */
    public static final int k_EPublishedFileInappropriateResult_Possible_VALUE = 3;
    /**
     * <code>k_EPublishedFileInappropriateResult_Likely = 4;</code>
     */
    public static final int k_EPublishedFileInappropriateResult_Likely_VALUE = 4;
    /**
     * <code>k_EPublishedFileInappropriateResult_VeryLikely = 5;</code>
     */
    public static final int k_EPublishedFileInappropriateResult_VeryLikely_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EPublishedFileInappropriateResult valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EPublishedFileInappropriateResult forNumber(int value) {
      switch (value) {
        case 0: return k_EPublishedFileInappropriateResult_NotScanned;
        case 1: return k_EPublishedFileInappropriateResult_VeryUnlikely;
        case 2: return k_EPublishedFileInappropriateResult_Unlikely;
        case 3: return k_EPublishedFileInappropriateResult_Possible;
        case 4: return k_EPublishedFileInappropriateResult_Likely;
        case 5: return k_EPublishedFileInappropriateResult_VeryLikely;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EPublishedFileInappropriateResult>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EPublishedFileInappropriateResult> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EPublishedFileInappropriateResult>() {
            public EPublishedFileInappropriateResult findValueByNumber(int number) {
              return EPublishedFileInappropriateResult.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.getDescriptor().getEnumTypes().get(2);
    }

    private static final EPublishedFileInappropriateResult[] VALUES = values();

    public static EPublishedFileInappropriateResult valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EPublishedFileInappropriateResult(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.chenerzhu.crawler.proxy.protobufs.EPublishedFileInappropriateResult)
  }

  /**
   * <pre>
   * 个人状态标志
   * </pre>
   *
   * Protobuf enum {@code com.chenerzhu.crawler.proxy.protobufs.EPersonaStateFlag}
   */
  public enum EPersonaStateFlag
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_EProfileCustomizationTypeInvalid0 = 0;</code>
     */
    k_EProfileCustomizationTypeInvalid0(0),
    /**
     * <code>k_EPersonaStateFlag_HasRichPresence = 1;</code>
     */
    k_EPersonaStateFlag_HasRichPresence(1),
    /**
     * <code>k_EPersonaStateFlag_InJoinableGame = 2;</code>
     */
    k_EPersonaStateFlag_InJoinableGame(2),
    /**
     * <code>k_EPersonaStateFlag_Golden = 4;</code>
     */
    k_EPersonaStateFlag_Golden(4),
    /**
     * <code>k_EPersonaStateFlag_RemotePlayTogether = 8;</code>
     */
    k_EPersonaStateFlag_RemotePlayTogether(8),
    /**
     * <code>k_EPersonaStateFlag_ClientTypeWeb = 32770;</code>
     */
    k_EPersonaStateFlag_ClientTypeWeb(32770),
    /**
     * <code>k_EPersonaStateFlag_ClientTypeMobile = 32772;</code>
     */
    k_EPersonaStateFlag_ClientTypeMobile(32772),
    /**
     * <code>k_EPersonaStateFlag_ClientTypeTenfoot = 32776;</code>
     */
    k_EPersonaStateFlag_ClientTypeTenfoot(32776),
    /**
     * <code>k_EPersonaStateFlag_ClientTypeVR = 32784;</code>
     */
    k_EPersonaStateFlag_ClientTypeVR(32784),
    /**
     * <code>k_EPersonaStateFlag_LaunchTypeGamepad = 32800;</code>
     */
    k_EPersonaStateFlag_LaunchTypeGamepad(32800),
    /**
     * <code>k_EPersonaStateFlag_LaunchTypeCompatTool = 32832;</code>
     */
    k_EPersonaStateFlag_LaunchTypeCompatTool(32832),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>k_EProfileCustomizationTypeInvalid0 = 0;</code>
     */
    public static final int k_EProfileCustomizationTypeInvalid0_VALUE = 0;
    /**
     * <code>k_EPersonaStateFlag_HasRichPresence = 1;</code>
     */
    public static final int k_EPersonaStateFlag_HasRichPresence_VALUE = 1;
    /**
     * <code>k_EPersonaStateFlag_InJoinableGame = 2;</code>
     */
    public static final int k_EPersonaStateFlag_InJoinableGame_VALUE = 2;
    /**
     * <code>k_EPersonaStateFlag_Golden = 4;</code>
     */
    public static final int k_EPersonaStateFlag_Golden_VALUE = 4;
    /**
     * <code>k_EPersonaStateFlag_RemotePlayTogether = 8;</code>
     */
    public static final int k_EPersonaStateFlag_RemotePlayTogether_VALUE = 8;
    /**
     * <code>k_EPersonaStateFlag_ClientTypeWeb = 32770;</code>
     */
    public static final int k_EPersonaStateFlag_ClientTypeWeb_VALUE = 32770;
    /**
     * <code>k_EPersonaStateFlag_ClientTypeMobile = 32772;</code>
     */
    public static final int k_EPersonaStateFlag_ClientTypeMobile_VALUE = 32772;
    /**
     * <code>k_EPersonaStateFlag_ClientTypeTenfoot = 32776;</code>
     */
    public static final int k_EPersonaStateFlag_ClientTypeTenfoot_VALUE = 32776;
    /**
     * <code>k_EPersonaStateFlag_ClientTypeVR = 32784;</code>
     */
    public static final int k_EPersonaStateFlag_ClientTypeVR_VALUE = 32784;
    /**
     * <code>k_EPersonaStateFlag_LaunchTypeGamepad = 32800;</code>
     */
    public static final int k_EPersonaStateFlag_LaunchTypeGamepad_VALUE = 32800;
    /**
     * <code>k_EPersonaStateFlag_LaunchTypeCompatTool = 32832;</code>
     */
    public static final int k_EPersonaStateFlag_LaunchTypeCompatTool_VALUE = 32832;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EPersonaStateFlag valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EPersonaStateFlag forNumber(int value) {
      switch (value) {
        case 0: return k_EProfileCustomizationTypeInvalid0;
        case 1: return k_EPersonaStateFlag_HasRichPresence;
        case 2: return k_EPersonaStateFlag_InJoinableGame;
        case 4: return k_EPersonaStateFlag_Golden;
        case 8: return k_EPersonaStateFlag_RemotePlayTogether;
        case 32770: return k_EPersonaStateFlag_ClientTypeWeb;
        case 32772: return k_EPersonaStateFlag_ClientTypeMobile;
        case 32776: return k_EPersonaStateFlag_ClientTypeTenfoot;
        case 32784: return k_EPersonaStateFlag_ClientTypeVR;
        case 32800: return k_EPersonaStateFlag_LaunchTypeGamepad;
        case 32832: return k_EPersonaStateFlag_LaunchTypeCompatTool;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EPersonaStateFlag>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EPersonaStateFlag> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EPersonaStateFlag>() {
            public EPersonaStateFlag findValueByNumber(int number) {
              return EPersonaStateFlag.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.getDescriptor().getEnumTypes().get(3);
    }

    private static final EPersonaStateFlag[] VALUES = values();

    public static EPersonaStateFlag valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EPersonaStateFlag(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.chenerzhu.crawler.proxy.protobufs.EPersonaStateFlag)
  }

  /**
   * <pre>
   * 内容检查提供者
   * </pre>
   *
   * Protobuf enum {@code com.chenerzhu.crawler.proxy.protobufs.EContentCheckProvider}
   */
  public enum EContentCheckProvider
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_EContentCheckProvider_Invalid = 0;</code>
     */
    k_EContentCheckProvider_Invalid(0),
    /**
     * <code>k_EContentCheckProvider_Google = 1;</code>
     */
    k_EContentCheckProvider_Google(1),
    /**
     * <code>k_EContentCheckProvider_Amazon = 2;</code>
     */
    k_EContentCheckProvider_Amazon(2),
    /**
     * <code>k_EContentCheckProvider_Local = 3;</code>
     */
    k_EContentCheckProvider_Local(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>k_EContentCheckProvider_Invalid = 0;</code>
     */
    public static final int k_EContentCheckProvider_Invalid_VALUE = 0;
    /**
     * <code>k_EContentCheckProvider_Google = 1;</code>
     */
    public static final int k_EContentCheckProvider_Google_VALUE = 1;
    /**
     * <code>k_EContentCheckProvider_Amazon = 2;</code>
     */
    public static final int k_EContentCheckProvider_Amazon_VALUE = 2;
    /**
     * <code>k_EContentCheckProvider_Local = 3;</code>
     */
    public static final int k_EContentCheckProvider_Local_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EContentCheckProvider valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EContentCheckProvider forNumber(int value) {
      switch (value) {
        case 0: return k_EContentCheckProvider_Invalid;
        case 1: return k_EContentCheckProvider_Google;
        case 2: return k_EContentCheckProvider_Amazon;
        case 3: return k_EContentCheckProvider_Local;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EContentCheckProvider>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EContentCheckProvider> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EContentCheckProvider>() {
            public EContentCheckProvider findValueByNumber(int number) {
              return EContentCheckProvider.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.getDescriptor().getEnumTypes().get(4);
    }

    private static final EContentCheckProvider[] VALUES = values();

    public static EContentCheckProvider valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EContentCheckProvider(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.chenerzhu.crawler.proxy.protobufs.EContentCheckProvider)
  }

  /**
   * <pre>
   * 个人资料定制类型
   * </pre>
   *
   * Protobuf enum {@code com.chenerzhu.crawler.proxy.protobufs.EProfileCustomizationType}
   */
  public enum EProfileCustomizationType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_EProfileCustomizationTypeInvalid = 0;</code>
     */
    k_EProfileCustomizationTypeInvalid(0),
    /**
     * <code>k_EProfileCustomizationTypeRareAchievementShowcase = 1;</code>
     */
    k_EProfileCustomizationTypeRareAchievementShowcase(1),
    /**
     * <code>k_EProfileCustomizationTypeGameCollector = 2;</code>
     */
    k_EProfileCustomizationTypeGameCollector(2),
    /**
     * <code>k_EProfileCustomizationTypeItemShowcase = 3;</code>
     */
    k_EProfileCustomizationTypeItemShowcase(3),
    /**
     * <code>k_EProfileCustomizationTypeTradeShowcase = 4;</code>
     */
    k_EProfileCustomizationTypeTradeShowcase(4),
    /**
     * <code>k_EProfileCustomizationTypeBadges = 5;</code>
     */
    k_EProfileCustomizationTypeBadges(5),
    /**
     * <code>k_EProfileCustomizationTypeFavoriteGame = 6;</code>
     */
    k_EProfileCustomizationTypeFavoriteGame(6),
    /**
     * <code>k_EProfileCustomizationTypeScreenshotShowcase = 7;</code>
     */
    k_EProfileCustomizationTypeScreenshotShowcase(7),
    /**
     * <code>k_EProfileCustomizationTypeCustomText = 8;</code>
     */
    k_EProfileCustomizationTypeCustomText(8),
    /**
     * <code>k_EProfileCustomizationTypeFavoriteGroup = 9;</code>
     */
    k_EProfileCustomizationTypeFavoriteGroup(9),
    /**
     * <code>k_EProfileCustomizationTypeRecommendation = 10;</code>
     */
    k_EProfileCustomizationTypeRecommendation(10),
    /**
     * <code>k_EProfileCustomizationTypeWorkshopItem = 11;</code>
     */
    k_EProfileCustomizationTypeWorkshopItem(11),
    /**
     * <code>k_EProfileCustomizationTypeMyWorkshop = 12;</code>
     */
    k_EProfileCustomizationTypeMyWorkshop(12),
    /**
     * <code>k_EProfileCustomizationTypeArtworkShowcase = 13;</code>
     */
    k_EProfileCustomizationTypeArtworkShowcase(13),
    /**
     * <code>k_EProfileCustomizationTypeVideoShowcase = 14;</code>
     */
    k_EProfileCustomizationTypeVideoShowcase(14),
    /**
     * <code>k_EProfileCustomizationTypeGuides = 15;</code>
     */
    k_EProfileCustomizationTypeGuides(15),
    /**
     * <code>k_EProfileCustomizationTypeMyGuides = 16;</code>
     */
    k_EProfileCustomizationTypeMyGuides(16),
    /**
     * <code>k_EProfileCustomizationTypeAchievements = 17;</code>
     */
    k_EProfileCustomizationTypeAchievements(17),
    /**
     * <code>k_EProfileCustomizationTypeGreenlight = 18;</code>
     */
    k_EProfileCustomizationTypeGreenlight(18),
    /**
     * <code>k_EProfileCustomizationTypeMyGreenlight = 19;</code>
     */
    k_EProfileCustomizationTypeMyGreenlight(19),
    /**
     * <code>k_EProfileCustomizationTypeSalien = 20;</code>
     */
    k_EProfileCustomizationTypeSalien(20),
    /**
     * <code>k_EProfileCustomizationTypeLoyaltyRewardReactions = 21;</code>
     */
    k_EProfileCustomizationTypeLoyaltyRewardReactions(21),
    /**
     * <code>k_EProfileCustomizationTypeSingleArtworkShowcase = 22;</code>
     */
    k_EProfileCustomizationTypeSingleArtworkShowcase(22),
    /**
     * <code>k_EProfileCustomizationTypeAchievementsCompletionist = 23;</code>
     */
    k_EProfileCustomizationTypeAchievementsCompletionist(23),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>k_EProfileCustomizationTypeInvalid = 0;</code>
     */
    public static final int k_EProfileCustomizationTypeInvalid_VALUE = 0;
    /**
     * <code>k_EProfileCustomizationTypeRareAchievementShowcase = 1;</code>
     */
    public static final int k_EProfileCustomizationTypeRareAchievementShowcase_VALUE = 1;
    /**
     * <code>k_EProfileCustomizationTypeGameCollector = 2;</code>
     */
    public static final int k_EProfileCustomizationTypeGameCollector_VALUE = 2;
    /**
     * <code>k_EProfileCustomizationTypeItemShowcase = 3;</code>
     */
    public static final int k_EProfileCustomizationTypeItemShowcase_VALUE = 3;
    /**
     * <code>k_EProfileCustomizationTypeTradeShowcase = 4;</code>
     */
    public static final int k_EProfileCustomizationTypeTradeShowcase_VALUE = 4;
    /**
     * <code>k_EProfileCustomizationTypeBadges = 5;</code>
     */
    public static final int k_EProfileCustomizationTypeBadges_VALUE = 5;
    /**
     * <code>k_EProfileCustomizationTypeFavoriteGame = 6;</code>
     */
    public static final int k_EProfileCustomizationTypeFavoriteGame_VALUE = 6;
    /**
     * <code>k_EProfileCustomizationTypeScreenshotShowcase = 7;</code>
     */
    public static final int k_EProfileCustomizationTypeScreenshotShowcase_VALUE = 7;
    /**
     * <code>k_EProfileCustomizationTypeCustomText = 8;</code>
     */
    public static final int k_EProfileCustomizationTypeCustomText_VALUE = 8;
    /**
     * <code>k_EProfileCustomizationTypeFavoriteGroup = 9;</code>
     */
    public static final int k_EProfileCustomizationTypeFavoriteGroup_VALUE = 9;
    /**
     * <code>k_EProfileCustomizationTypeRecommendation = 10;</code>
     */
    public static final int k_EProfileCustomizationTypeRecommendation_VALUE = 10;
    /**
     * <code>k_EProfileCustomizationTypeWorkshopItem = 11;</code>
     */
    public static final int k_EProfileCustomizationTypeWorkshopItem_VALUE = 11;
    /**
     * <code>k_EProfileCustomizationTypeMyWorkshop = 12;</code>
     */
    public static final int k_EProfileCustomizationTypeMyWorkshop_VALUE = 12;
    /**
     * <code>k_EProfileCustomizationTypeArtworkShowcase = 13;</code>
     */
    public static final int k_EProfileCustomizationTypeArtworkShowcase_VALUE = 13;
    /**
     * <code>k_EProfileCustomizationTypeVideoShowcase = 14;</code>
     */
    public static final int k_EProfileCustomizationTypeVideoShowcase_VALUE = 14;
    /**
     * <code>k_EProfileCustomizationTypeGuides = 15;</code>
     */
    public static final int k_EProfileCustomizationTypeGuides_VALUE = 15;
    /**
     * <code>k_EProfileCustomizationTypeMyGuides = 16;</code>
     */
    public static final int k_EProfileCustomizationTypeMyGuides_VALUE = 16;
    /**
     * <code>k_EProfileCustomizationTypeAchievements = 17;</code>
     */
    public static final int k_EProfileCustomizationTypeAchievements_VALUE = 17;
    /**
     * <code>k_EProfileCustomizationTypeGreenlight = 18;</code>
     */
    public static final int k_EProfileCustomizationTypeGreenlight_VALUE = 18;
    /**
     * <code>k_EProfileCustomizationTypeMyGreenlight = 19;</code>
     */
    public static final int k_EProfileCustomizationTypeMyGreenlight_VALUE = 19;
    /**
     * <code>k_EProfileCustomizationTypeSalien = 20;</code>
     */
    public static final int k_EProfileCustomizationTypeSalien_VALUE = 20;
    /**
     * <code>k_EProfileCustomizationTypeLoyaltyRewardReactions = 21;</code>
     */
    public static final int k_EProfileCustomizationTypeLoyaltyRewardReactions_VALUE = 21;
    /**
     * <code>k_EProfileCustomizationTypeSingleArtworkShowcase = 22;</code>
     */
    public static final int k_EProfileCustomizationTypeSingleArtworkShowcase_VALUE = 22;
    /**
     * <code>k_EProfileCustomizationTypeAchievementsCompletionist = 23;</code>
     */
    public static final int k_EProfileCustomizationTypeAchievementsCompletionist_VALUE = 23;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EProfileCustomizationType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EProfileCustomizationType forNumber(int value) {
      switch (value) {
        case 0: return k_EProfileCustomizationTypeInvalid;
        case 1: return k_EProfileCustomizationTypeRareAchievementShowcase;
        case 2: return k_EProfileCustomizationTypeGameCollector;
        case 3: return k_EProfileCustomizationTypeItemShowcase;
        case 4: return k_EProfileCustomizationTypeTradeShowcase;
        case 5: return k_EProfileCustomizationTypeBadges;
        case 6: return k_EProfileCustomizationTypeFavoriteGame;
        case 7: return k_EProfileCustomizationTypeScreenshotShowcase;
        case 8: return k_EProfileCustomizationTypeCustomText;
        case 9: return k_EProfileCustomizationTypeFavoriteGroup;
        case 10: return k_EProfileCustomizationTypeRecommendation;
        case 11: return k_EProfileCustomizationTypeWorkshopItem;
        case 12: return k_EProfileCustomizationTypeMyWorkshop;
        case 13: return k_EProfileCustomizationTypeArtworkShowcase;
        case 14: return k_EProfileCustomizationTypeVideoShowcase;
        case 15: return k_EProfileCustomizationTypeGuides;
        case 16: return k_EProfileCustomizationTypeMyGuides;
        case 17: return k_EProfileCustomizationTypeAchievements;
        case 18: return k_EProfileCustomizationTypeGreenlight;
        case 19: return k_EProfileCustomizationTypeMyGreenlight;
        case 20: return k_EProfileCustomizationTypeSalien;
        case 21: return k_EProfileCustomizationTypeLoyaltyRewardReactions;
        case 22: return k_EProfileCustomizationTypeSingleArtworkShowcase;
        case 23: return k_EProfileCustomizationTypeAchievementsCompletionist;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EProfileCustomizationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EProfileCustomizationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EProfileCustomizationType>() {
            public EProfileCustomizationType findValueByNumber(int number) {
              return EProfileCustomizationType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.getDescriptor().getEnumTypes().get(5);
    }

    private static final EProfileCustomizationType[] VALUES = values();

    public static EProfileCustomizationType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EProfileCustomizationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.chenerzhu.crawler.proxy.protobufs.EProfileCustomizationType)
  }

  public interface NoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chenerzhu.crawler.proxy.protobufs.NoResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 空响应消息
   * </pre>
   *
   * Protobuf type {@code com.chenerzhu.crawler.proxy.protobufs.NoResponse}
   */
  public static final class NoResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chenerzhu.crawler.proxy.protobufs.NoResponse)
      NoResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NoResponse.newBuilder() to construct.
    private NoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NoResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NoResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.internal_static_com_chenerzhu_crawler_proxy_protobufs_NoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.internal_static_com_chenerzhu_crawler_proxy_protobufs_NoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse.class, com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse)) {
        return super.equals(obj);
      }
      com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse other = (com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 空响应消息
     * </pre>
     *
     * Protobuf type {@code com.chenerzhu.crawler.proxy.protobufs.NoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chenerzhu.crawler.proxy.protobufs.NoResponse)
        com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.internal_static_com_chenerzhu_crawler_proxy_protobufs_NoResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.internal_static_com_chenerzhu_crawler_proxy_protobufs_NoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse.class, com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse.Builder.class);
      }

      // Construct using com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.internal_static_com_chenerzhu_crawler_proxy_protobufs_NoResponse_descriptor;
      }

      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse getDefaultInstanceForType() {
        return com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse build() {
        com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse buildPartial() {
        com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse result = new com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse) {
          return mergeFrom((com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse other) {
        if (other == com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chenerzhu.crawler.proxy.protobufs.NoResponse)
    }

    // @@protoc_insertion_point(class_scope:com.chenerzhu.crawler.proxy.protobufs.NoResponse)
    private static final com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse();
    }

    public static com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NoResponse>
        PARSER = new com.google.protobuf.AbstractParser<NoResponse>() {
      @java.lang.Override
      public NoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NoResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chenerzhu.crawler.proxy.protobufs.EnumsPb2.NoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chenerzhu_crawler_proxy_protobufs_NoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chenerzhu_crawler_proxy_protobufs_NoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017enums_pb2.proto\022%com.chenerzhu.crawler" +
      ".proxy.protobufs\"\014\n\nNoResponse*\200\n\n\027EPubl" +
      "ishedFileQueryType\022)\n%k_PublishedFileQue" +
      "ryType_RankedByVote\020\000\0224\n0k_PublishedFile" +
      "QueryType_RankedByPublicationDate\020\001\022B\n>k" +
      "_PublishedFileQueryType_AcceptedForGameR" +
      "ankedByAcceptanceDate\020\002\022*\n&k_PublishedFi" +
      "leQueryType_RankedByTrend\020\003\022F\nBk_Publish" +
      "edFileQueryType_FavoritedByFriendsRanked" +
      "ByPublicationDate\020\004\022D\n@k_PublishedFileQu" +
      "eryType_CreatedByFriendsRankedByPublicat" +
      "ionDate\020\005\0225\n1k_PublishedFileQueryType_Ra" +
      "nkedByNumTimesReported\020\006\022J\nFk_PublishedF" +
      "ileQueryType_CreatedByFollowedUsersRanke" +
      "dByPublicationDate\020\007\022(\n$k_PublishedFileQ" +
      "ueryType_NotYetRated\020\010\022=\n9k_PublishedFil" +
      "eQueryType_RankedByTotalUniqueSubscripti" +
      "ons\020\t\0222\n.k_PublishedFileQueryType_Ranked" +
      "ByTotalVotesAsc\020\n\022,\n(k_PublishedFileQuer" +
      "yType_RankedByVotesUp\020\013\022/\n+k_PublishedFi" +
      "leQueryType_RankedByTextSearch\020\014\0222\n.k_Pu" +
      "blishedFileQueryType_RankedByPlaytimeTre" +
      "nd\020\r\0222\n.k_PublishedFileQueryType_RankedB" +
      "yTotalPlaytime\020\016\0229\n5k_PublishedFileQuery" +
      "Type_RankedByAveragePlaytimeTrend\020\017\022<\n8k" +
      "_PublishedFileQueryType_RankedByLifetime" +
      "AveragePlaytime\020\020\022:\n6k_PublishedFileQuer" +
      "yType_RankedByPlaytimeSessionsTrend\020\021\022=\n" +
      "9k_PublishedFileQueryType_RankedByLifeti" +
      "mePlaytimeSessions\020\022\022?\n;k_PublishedFileQ" +
      "ueryType_RankedByInappropriateContentRat" +
      "ing\020\023\0224\n0k_PublishedFileQueryType_Ranked" +
      "ByBanContentCheck\020\024\0224\n0k_PublishedFileQu" +
      "eryType_RankedByLastUpdatedDate\020\025*\274\001\n#EP" +
      "ublishedFileInappropriateProvider\0221\n-k_E" +
      "PublishedFileInappropriateProvider_Inval" +
      "id\020\000\0220\n,k_EPublishedFileInappropriatePro" +
      "vider_Google\020\001\0220\n,k_EPublishedFileInappr" +
      "opriateProvider_Amazon\020\002*\325\002\n!EPublishedF" +
      "ileInappropriateResult\0222\n.k_EPublishedFi" +
      "leInappropriateResult_NotScanned\020\000\0224\n0k_" +
      "EPublishedFileInappropriateResult_VeryUn" +
      "likely\020\001\0220\n,k_EPublishedFileInappropriat" +
      "eResult_Unlikely\020\002\0220\n,k_EPublishedFileIn" +
      "appropriateResult_Possible\020\003\022.\n*k_EPubli" +
      "shedFileInappropriateResult_Likely\020\004\0222\n." +
      "k_EPublishedFileInappropriateResult_Very" +
      "Likely\020\005*\340\003\n\021EPersonaStateFlag\022\'\n#k_EPro" +
      "fileCustomizationTypeInvalid0\020\000\022\'\n#k_EPe" +
      "rsonaStateFlag_HasRichPresence\020\001\022&\n\"k_EP" +
      "ersonaStateFlag_InJoinableGame\020\002\022\036\n\032k_EP" +
      "ersonaStateFlag_Golden\020\004\022*\n&k_EPersonaSt" +
      "ateFlag_RemotePlayTogether\020\010\022\'\n!k_EPerso" +
      "naStateFlag_ClientTypeWeb\020\202\200\002\022*\n$k_EPers" +
      "onaStateFlag_ClientTypeMobile\020\204\200\002\022+\n%k_E" +
      "PersonaStateFlag_ClientTypeTenfoot\020\210\200\002\022&" +
      "\n k_EPersonaStateFlag_ClientTypeVR\020\220\200\002\022+" +
      "\n%k_EPersonaStateFlag_LaunchTypeGamepad\020" +
      "\240\200\002\022.\n(k_EPersonaStateFlag_LaunchTypeCom" +
      "patTool\020\300\200\002*\247\001\n\025EContentCheckProvider\022#\n" +
      "\037k_EContentCheckProvider_Invalid\020\000\022\"\n\036k_" +
      "EContentCheckProvider_Google\020\001\022\"\n\036k_ECon" +
      "tentCheckProvider_Amazon\020\002\022!\n\035k_EContent" +
      "CheckProvider_Local\020\003*\354\010\n\031EProfileCustom" +
      "izationType\022&\n\"k_EProfileCustomizationTy" +
      "peInvalid\020\000\0226\n2k_EProfileCustomizationTy" +
      "peRareAchievementShowcase\020\001\022,\n(k_EProfil" +
      "eCustomizationTypeGameCollector\020\002\022+\n\'k_E" +
      "ProfileCustomizationTypeItemShowcase\020\003\022," +
      "\n(k_EProfileCustomizationTypeTradeShowca" +
      "se\020\004\022%\n!k_EProfileCustomizationTypeBadge" +
      "s\020\005\022+\n\'k_EProfileCustomizationTypeFavori" +
      "teGame\020\006\0221\n-k_EProfileCustomizationTypeS" +
      "creenshotShowcase\020\007\022)\n%k_EProfileCustomi" +
      "zationTypeCustomText\020\010\022,\n(k_EProfileCust" +
      "omizationTypeFavoriteGroup\020\t\022-\n)k_EProfi" +
      "leCustomizationTypeRecommendation\020\n\022+\n\'k" +
      "_EProfileCustomizationTypeWorkshopItem\020\013" +
      "\022)\n%k_EProfileCustomizationTypeMyWorksho" +
      "p\020\014\022.\n*k_EProfileCustomizationTypeArtwor" +
      "kShowcase\020\r\022,\n(k_EProfileCustomizationTy" +
      "peVideoShowcase\020\016\022%\n!k_EProfileCustomiza" +
      "tionTypeGuides\020\017\022\'\n#k_EProfileCustomizat" +
      "ionTypeMyGuides\020\020\022+\n\'k_EProfileCustomiza" +
      "tionTypeAchievements\020\021\022)\n%k_EProfileCust" +
      "omizationTypeGreenlight\020\022\022+\n\'k_EProfileC" +
      "ustomizationTypeMyGreenlight\020\023\022%\n!k_EPro" +
      "fileCustomizationTypeSalien\020\024\0225\n1k_EProf" +
      "ileCustomizationTypeLoyaltyRewardReactio" +
      "ns\020\025\0224\n0k_EProfileCustomizationTypeSingl" +
      "eArtworkShowcase\020\026\0228\n4k_EProfileCustomiz" +
      "ationTypeAchievementsCompletionist\020\027b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_chenerzhu_crawler_proxy_protobufs_NoResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chenerzhu_crawler_proxy_protobufs_NoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chenerzhu_crawler_proxy_protobufs_NoResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
